package dev.eryalabs.nenya.delivery

import java.io.File
import java.lang.reflect.Executable
import java.lang.reflect.Method
import java.lang.reflect.Modifier
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * The structural half of §10.4's ordering and of STOP RULE 12, enforced by reflection rather
 * than by review.
 *
 * §11.3 invariant 4 says `settled` is reachable only after the buyer's own hash computation.
 * A code review can only assert that today's code obeys that; this file asserts it about
 * whatever is in the package tomorrow, which is when somebody adds
 * `verifyPlaintextBytes(..., providerSaysDelivered: Boolean)` in a hurry, or a second factory
 * that hands out a [DeliveryEvidence] without a [ServedBytesVerified] in front of it.
 *
 * The sweep is the one the payment package's `PaymentStructureTest` specifies, over
 * `dev/eryalabs/nenya/delivery`, and every note there applies here:
 *
 * - **`java.lang.reflect` only.** `kotlin-reflect` is not on any classpath and STOP RULE 11
 *   forbids adding one. `KClass.members` and `KClass.constructors` compile and then throw
 *   `KotlinReflectionNotSupportedError`; `kotlin.reflect.full.*` does not compile at all.
 * - **`getResources`, plural.** The singular form resolves to the **test** output directory,
 *   because `build/classes/kotlin/jvm/test` precedes `build/classes/kotlin/jvm/main` on the test
 *   runtime classpath and this repo mirrors package names into its test tree. A sweep built on
 *   it would enumerate this very file's class, never see [DeliveryEvidence], and pass with the
 *   implementation entirely absent.
 * - **Classes asserted by name.** A count is satisfied by whatever the wrong classpath entry
 *   happened to contain, which is exactly the failure the plural form exists to avoid.
 * - **The generic form, never the erased one.** `parameterTypes` and `returnType` report the
 *   type after erasure, so `fun x(flags: List<Boolean>)` satisfies "no published member accepts
 *   a Boolean" and `fun x(): List<DeliveryEvidence>` satisfies "there is exactly one door into
 *   each evidence type" while handing a caller the thing the rule forbids, wrapped in a
 *   collection. Every type inspection below therefore reads `genericParameterTypes` /
 *   `genericReturnType` and matches on `typeName`, which prints the parameterised form. Each
 *   predicate sweep carries a probe class at the foot of this file that proves it: the probe is
 *   fed to the sweep's **own** named predicate, because a control exercising a second copy of
 *   the check would prove nothing about the first. Counting a constructor's arity with
 *   `parameterTypes.size` is not a type inspection and is left as it is.
 */
class DeliveryStructureTest {

    private companion object {

        const val PACKAGE: String = "dev.eryalabs.nenya.delivery"

        /** The classes this sweep is *about*, by name rather than by count. */
        val EXPECTED_BY_NAME: Set<String> = setOf(
            "DeliverableCommitment",
            "DeliverableRelease",
            "DeliverableHash",
            "ServedBytesVerified",
            "DeliveryEvidence",
            "DeliveryCheck",
        )

        /**
         * Every place on the published surface where a `String` may be a parameter, pinned by
         * name. A new one turns this red and forces a human to say why it is not a status
         * string being smuggled in as evidence of delivery. Each of these is either a hex
         * reader (§4.3's encoding, not a status), a MIME type §10.3 compares byte-identically,
         * a diagnostic message, or a compiler-generated enum lookup.
         */
        val STRING_PARAMETERS_PERMITTED: Set<String> = setOf(
            "DeliverableHash\$Companion.ofHex",  // §4.3 hex, 64 characters, either case
            "DeliverableCommitment.<init>",      // §10.1's ["m", ...] value
            "DeliverableRelease.<init>",         // §10.3's ["file-type", ...] value, nullable
            "DeliveryException.<init>",          // the human-readable rejection message
            "DeliveryCheck.valueOf",             // generated by the Kotlin compiler for enums
            "DeliveryRejection.valueOf",         // ditto
        )

        fun mainClasses(): List<Class<*>> {
            val loader = DeliveryStructureTest::class.java.classLoader
            val urls = loader.getResources(PACKAGE.replace('.', '/')).toList()
            val main = urls.firstOrNull { it.path.contains("/classes/kotlin/jvm/main/") }
                ?: fail(
                    "no /classes/kotlin/jvm/main/ URL for $PACKAGE among $urls — the sweep would " +
                        "otherwise enumerate the test output directory and pass with no implementation",
                )
            val directory = File(main.toURI())
            val files = directory.listFiles { file: File -> file.name.endsWith(".class") }
                ?: fail("${directory.absolutePath} is not a readable directory")
            assertTrue(files.isNotEmpty(), "${directory.absolutePath} holds no classes")
            // The class files this package compiled to at commit 6432814, pinned as a floor so a
            // partial output directory after a source-layout move goes red instead of sweeping less.
            val pinned = 14
            assertTrue(
                files.size >= pinned,
                "${directory.absolutePath} holds ${files.size} class file(s); at least $pinned were pinned",
            )
            return files.map { Class.forName("$PACKAGE.${it.name.removeSuffix(".class")}", false, loader) }
        }

        fun publishedClasses(): List<Class<*>> =
            mainClasses().filter { Modifier.isPublic(it.modifiers) && !it.isSynthetic }

        /** Constructors and own public methods, minus everything a client cannot name. */
        fun publishedExecutables(type: Class<*>): List<Executable> =
            type.constructors.toList() +
                type.methods.filter {
                    it.declaringClass == type && !it.isSynthetic && !it.isBridge && '$' !in it.name
                }

        fun label(type: Class<*>, executable: Executable): String {
            val simple = type.name.removePrefix("$PACKAGE.")
            val member = if (executable is java.lang.reflect.Constructor<*>) "<init>" else executable.name
            return "$simple.$member"
        }

        fun evidenceType(name: String): Class<*> = mainClasses().single { it.name == "$PACKAGE.$name" }

        /** The two types §10.4's ordering is about, and the only two a published door may hand out. */
        val EVIDENCE_TYPES: List<String> = listOf("ServedBytesVerified", "DeliveryEvidence")

        /**
         * The generic type names on [executable]'s parameter list — `java.util.List<java.lang.Boolean>`
         * where `parameterTypes` would have said `java.util.List`.
         */
        fun parameterTypeNames(executable: Executable): List<String> =
            executable.genericParameterTypes.map { it.typeName }

        /** The generic type name [executable] returns, or `null` when it is a constructor. */
        fun returnTypeName(executable: Executable): String? =
            (executable as? Method)?.genericReturnType?.typeName

        /**
         * Whether [typeName] names [sought] itself or names it inside a generic's type arguments.
         *
         * A bare `contains` is wrong: `java.lang.StringBuilder` contains `java.lang.String`. So the
         * match is on a whole type token — the character either side must not continue an identifier.
         * A `Regex` would say the same thing and STOP RULE forbids one here.
         */
        fun namesType(typeName: String, sought: String): Boolean {
            var from = 0
            while (true) {
                val at = typeName.indexOf(sought, from)
                if (at < 0) return false
                val before = if (at == 0) ' ' else typeName[at - 1]
                val afterAt = at + sought.length
                val after = if (afterAt >= typeName.length) ' ' else typeName[afterAt]
                if (!continuesIdentifier(before) && !continuesIdentifier(after)) return true
                from = at + 1
            }
        }

        private fun continuesIdentifier(c: Char): Boolean =
            c.isLetterOrDigit() || c == '.' || c == '$' || c == '_'

        /**
         * The first parameter of [executable] that mentions a Boolean anywhere in its generic type,
         * or `null` if none does. The sweep and its probe both call this, and nothing re-implements it.
         *
         * **Both spellings.** A bare Kotlin `Boolean` parameter erases to the JVM primitive, whose
         * `typeName` is `boolean`; inside a generic it is boxed and reads `java.lang.Boolean`. A
         * predicate checking only one of the two would be a fresh instance of the same defect.
         *
         * Parameters only, which is the rule as it was written: `equals(Any?): Boolean` returns one
         * and is not a function that can be *told* whether a delivery happened.
         */
        fun booleanParameterIn(executable: Executable): String? =
            parameterTypeNames(executable).firstOrNull {
                namesType(it, "boolean") || namesType(it, "java.lang.Boolean")
            }

        /**
         * The first parameter of [executable] that mentions a `String` anywhere in its generic type,
         * or `null` if none does. Shared by the pinned-list sweep and its probe.
         */
        fun stringParameterIn(executable: Executable): String? =
            parameterTypeNames(executable).firstOrNull { namesType(it, "java.lang.String") }

        /**
         * Which of [EVIDENCE_TYPES] [executable]'s return type names — directly or from inside a
         * generic. `List<DeliveryEvidence>` is a door into [DeliveryEvidence] as surely as
         * [DeliveryEvidence] is; the erased read this replaced saw only `java.util.List`.
         */
        fun evidenceTypesReturnedBy(executable: Executable): List<String> {
            val returned = returnTypeName(executable) ?: return emptyList()
            return EVIDENCE_TYPES.filter { namesType(returned, "$PACKAGE.$it") }
        }
    }

    @Test
    fun `the sweep finds the classes it is about, by name`() {
        val found = mainClasses().map { it.name.removePrefix("$PACKAGE.") }.toSet()

        for (expected in EXPECTED_BY_NAME) {
            assertTrue(
                expected in found,
                "$expected was not among the main classes of $PACKAGE; found $found",
            )
        }
    }

    @Test
    fun `neither evidence type has a constructor for a client to reach`() {
        for (name in listOf("ServedBytesVerified", "DeliveryEvidence")) {
            val type = evidenceType(name)

            assertTrue(type.isInterface, "$name: an interface has no constructor to synthesise for")
            assertEquals(
                0,
                type.constructors.size,
                "$name: a private constructor plus a companion factory emits a *public synthetic* " +
                    "constructor with a trailing DefaultConstructorMarker, which a Java client can " +
                    "call with null",
            )
            assertTrue(
                type.declaredConstructors.none { it.isSynthetic },
                "$name: not even a synthetic constructor may exist",
            )
            assertTrue(
                type.isSealed,
                "$name: the JVM PermittedSubclasses attribute is what stops another module " +
                    "implementing this interface; it is emitted only from JDK 17 upward, so a " +
                    "toolchain drop would silently remove it while every other assertion stayed green",
            )
        }
    }

    @Test
    fun `every implementation of either evidence type is non-public`() {
        val classes = mainClasses()

        for (name in listOf("ServedBytesVerified", "DeliveryEvidence")) {
            val type = evidenceType(name)
            val implementations = classes.filter { it != type && type.isAssignableFrom(it) }

            assertTrue(
                implementations.isNotEmpty(),
                "$name: the sweep must actually find an implementation; the assertions above are " +
                    "true of any interface at all and would pass over a public one",
            )
            for (implementation in implementations) {
                assertFalse(
                    Modifier.isPublic(implementation.modifiers),
                    "${implementation.name} implements $name and is JVM-public, so a client can " +
                        "construct evidence of a delivery that never happened",
                )
            }
        }
    }

    @Test
    fun `no published constructor or method accepts a Boolean`() {
        // Its own by-name guard rather than only the `inspected` floor below. Every other test
        // here would turn red if `mainClasses()` started resolving to the test output directory;
        // this one would not, because the test tree alone satisfies a bare member count.
        val published = publishedClasses()
        val found = published.map { it.name.removePrefix("$PACKAGE.") }.toSet()
        assertTrue(
            EXPECTED_BY_NAME.all { it in found },
            "the Boolean sweep must be looking at $EXPECTED_BY_NAME, not at whatever classpath " +
                "entry it happened to land on; it found $found",
        )

        var inspected = 0
        for (type in published) {
            for (executable in publishedExecutables(type)) {
                inspected++
                val offender = booleanParameterIn(executable)
                assertNull(
                    offender,
                    "${label(type, executable)} takes a Boolean, as `$offender`. §11.3 invariant 4: " +
                        "`settled` is reachable only after the buyer's own hash computation, and a " +
                        "function that can be told the answer is not a computation — wrapping the " +
                        "answer in a collection does not make it a computation either",
                )
            }
        }
        assertTrue(inspected > 10, "the sweep inspected only $inspected members, which is not the package")
    }

    @Test
    fun `every published String parameter is on the pinned list`() {
        val found = mutableSetOf<String>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                if (stringParameterIn(executable) != null) {
                    found += label(type, executable)
                }
            }
        }

        assertEquals(
            STRING_PARAMETERS_PERMITTED,
            found,
            "the set of published members taking a String must match the pinned list exactly — and a " +
                "`List<String>` or a `Map<String, ...>` is taking a String. A new entry may be a " +
                "status string arriving as evidence of delivery; a missing entry means the sweep " +
                "stopped seeing the package.",
        )
    }

    /**
     * A whole-list equality, so it carries no probe and none is missing: an exact pin cannot be
     * erasure-blind in the dangerous direction, because a smuggled `List<PaymentHash>` parameter
     * erases to `List` and fails the pin outright. It is read in the generic form anyway, so the
     * expected side reads as what a human would write.
     *
     * The expected names are built with `typeName` rather than `name` on purpose:
     * `ByteArray::class.java.name` is `"[B"` while its `typeName` is `"byte[]"`, and it is the
     * latter that `genericParameterTypes` reports.
     */
    @Test
    fun `the served-bytes verifier takes a commitment, bytes and a bound, and nothing that can assert`() {
        val companion = evidenceType("ServedBytesVerified\$Companion")
        val verify = companion.methods.single { it.name == "verifyServedBytes" }

        assertEquals(
            listOf(
                DeliverableCommitment::class.java.typeName,
                ByteArray::class.java.typeName,
                java.lang.Long.TYPE.typeName,
            ),
            verify.genericParameterTypes.map { it.typeName },
            "§10.4 step 1 takes the commitment, the bytes and §4.3's bound; anything else on this " +
                "parameter list is something a counterparty could say",
        )
        assertEquals(ServedBytesVerified::class.java.typeName, verify.genericReturnType.typeName)
    }

    /** A whole-list equality, so no probe. See the note on the served-bytes pin above. */
    @Test
    fun `the plaintext verifier can only be reached with a verified served-bytes value`() {
        val companion = evidenceType("DeliveryEvidence\$Companion")
        val verify = companion.methods.single { it.name == "verifyPlaintextBytes" }

        assertEquals(
            listOf(ServedBytesVerified::class.java.typeName, ByteArray::class.java.typeName),
            verify.genericParameterTypes.map { it.typeName },
            "§10.4's ordering is enforced by the type system: there is no way to reach the ox check " +
                "without having passed the x check, and this parameter list is that enforcement",
        )
        assertEquals(DeliveryEvidence::class.java.typeName, verify.genericReturnType.typeName)
    }

    /**
     * The trap the payment package fell into and had to be pulled back out of: the sealed
     * interface protects the *evidence* type, and does nothing at all for the value types it
     * holds. [DeliverableHash] uses the private-constructor-plus-companion-factory idiom, which
     * emits a JVM-public synthetic constructor with a trailing `DefaultConstructorMarker` — so
     * a Java client can write `new DeliverableHash(threeBytes, null)` and hold a 3-byte "SHA-256
     * commitment" that §4.3 says must have been refused. The invariant therefore lives in
     * `init`, which that constructor also runs, and this test is what proves it does.
     */
    @Test
    fun `the synthetic constructor of DeliverableHash still enforces the length`() {
        val type = evidenceType("DeliverableHash")
        val synthetic = type.declaredConstructors.single { it.parameterTypes.size == 2 }
        synthetic.isAccessible = true

        val thrown = assertFailsWith<java.lang.reflect.InvocationTargetException> {
            synthetic.newInstance(ByteArray(3), null)
        }
        val cause = thrown.cause
        assertTrue(cause is DeliveryException, "expected a DeliveryException, got $cause")
        assertEquals(
            DeliveryRejection.WRONG_LENGTH,
            cause.reason,
            "§4.3 requires rejecting a value of the wrong length rather than padding or truncating " +
                "it, on every construction path and not only on the one Kotlin call sites use",
        )
    }

    @Test
    fun `the synthetic constructor of DeliverableHash copies the caller's array on the way in`() {
        val type = evidenceType("DeliverableHash")
        val synthetic = type.declaredConstructors.single { it.parameterTypes.size == 2 }
        synthetic.isAccessible = true
        val caller = DeliveryFixtures.sha256(byteArrayOf(1, 2, 3))

        val hash = synthetic.newInstance(caller, null) as DeliverableHash
        val before = hash.toHex()
        caller.fill(0)

        assertEquals(
            before,
            hash.toHex(),
            "the caller of that constructor keeps its own reference, so a commitment that did not " +
                "copy on the way in could be rewritten after it was read",
        )
    }

    @Test
    fun `there is exactly one door into each evidence type`() {
        val doors = mutableMapOf<String, MutableList<String>>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                for (name in evidenceTypesReturnedBy(executable)) {
                    doors.getOrPut(name) { mutableListOf() } += label(type, executable)
                }
            }
        }

        assertEquals(
            mapOf(
                "ServedBytesVerified" to listOf("ServedBytesVerified\$Companion.verifyServedBytes"),
                "DeliveryEvidence" to listOf("DeliveryEvidence\$Companion.verifyPlaintextBytes"),
            ),
            doors,
            "a second published function returning one of these would be a second way to obtain " +
                "delivery evidence, and §10.4's ordering is only as strong as the narrowest door — " +
                "a function returning List<DeliveryEvidence> is such a door, which is why this reads " +
                "the generic return type and not the erased one",
        )
    }

    /**
     * The control that proves the Boolean sweep above is not erasure-blind.
     *
     * Without it, "no published member accepts a Boolean" is satisfied by a predicate that never
     * matches a `List<Boolean>` — which is precisely what the erased-type check it replaced was.
     * The probe is fed to [booleanParameterIn], the sweep's own predicate; a control run against a
     * second copy of the check would say nothing about the one the sweep runs.
     */
    @Test
    fun `the Boolean sweep catches a Boolean hidden inside a generic type`() {
        val probe = BooleanCollectionProbe::class.java

        for (name in listOf("wrapped", "keyed", "nested")) {
            val method = probe.methods.single { it.name == name }
            assertNotNull(
                booleanParameterIn(method),
                "BooleanCollectionProbe.$name hides a Boolean and the sweep missed it — " +
                    "${method.genericParameterTypes.single().typeName} erases past an erased-type check",
            )
        }
        assertNotNull(
            booleanParameterIn(probe.methods.single { it.name == "direct" }),
            "the converted sweep must still catch everything the erased one caught, a bare " +
                "`boolean` parameter first of all",
        )
        assertNull(
            booleanParameterIn(probe.methods.single { it.name == "permitted" }),
            "the rule is about Booleans, not about generics; a sweep that rejected every " +
                "parameterised parameter would pass its probe and forbid the wrong thing",
        )
    }

    /**
     * The control that proves the String sweep above is not erasure-blind.
     *
     * The pinned list is only as good as the predicate that populates it: a `List<String>`
     * parameter that erases to `java.util.List` never reaches the list, so a status string could be
     * smuggled onto the published surface inside a collection and the exact-set assertion would
     * stay green. Fed to [stringParameterIn], the sweep's own predicate.
     */
    @Test
    fun `the String sweep catches a String hidden inside a generic type`() {
        val probe = StringCollectionProbe::class.java

        for (name in listOf("wrapped", "keyed", "nested")) {
            val method = probe.methods.single { it.name == name }
            assertNotNull(
                stringParameterIn(method),
                "StringCollectionProbe.$name hides a String and the sweep missed it — " +
                    "${method.genericParameterTypes.single().typeName} erases past an erased-type check",
            )
        }
        assertNotNull(
            stringParameterIn(probe.methods.single { it.name == "direct" }),
            "the converted sweep must still catch a bare String parameter, which is what the " +
                "pinned list was written about",
        )
        assertNull(
            stringParameterIn(probe.methods.single { it.name == "permitted" }),
            "the rule is about Strings, not about generics; a `List<Long>` parameter is neither a " +
                "status string nor a smuggled one",
        )
        assertNull(
            stringParameterIn(probe.methods.single { it.name == "lookalike" }),
            "`java.lang.StringBuilder` contains `java.lang.String` as a substring, so a `contains` " +
                "match would pin a member that takes no String at all",
        )
    }

    /**
     * The control that proves the evidence-door sweep above is not erasure-blind.
     *
     * A published `fun x(): List<DeliveryEvidence>` is a second door into the evidence type and
     * §10.4's ordering is only as strong as the narrowest one, yet it erases to `java.util.List`
     * and the sweep this replaced would not have recorded it. Fed to [evidenceTypesReturnedBy].
     */
    @Test
    fun `the evidence-door sweep catches an evidence type hidden inside a generic return`() {
        val probe = EvidenceDoorProbe::class.java

        for (name in listOf("wrapped", "keyed", "nested")) {
            val method = probe.methods.single { it.name == name }
            assertTrue(
                evidenceTypesReturnedBy(method).isNotEmpty(),
                "EvidenceDoorProbe.$name hands out evidence and the sweep missed it — " +
                    "${method.genericReturnType.typeName} erases past an erased-type check",
            )
        }
        assertEquals(
            listOf("ServedBytesVerified"),
            evidenceTypesReturnedBy(probe.methods.single { it.name == "direct" }),
            "the converted sweep must still record the plain return the erased one recorded",
        )
        assertEquals(
            emptyList<String>(),
            evidenceTypesReturnedBy(probe.methods.single { it.name == "permitted" }),
            "a door is a function that hands out evidence, not any function with a generic return",
        )
        val constructors = probe.declaredConstructors
        assertTrue(constructors.isNotEmpty(), "the constructor leg of this control must inspect something")
        for (constructor in constructors) {
            assertEquals(
                emptyList<String>(),
                evidenceTypesReturnedBy(constructor),
                "a constructor returns nothing and must not be read as a door; the erased sweep " +
                    "skipped it with `as? Method` and so must this one",
            )
        }
    }

    /**
     * A probe, not a fixture: three shapes STOP RULE 12 forbids and the erased check could not see,
     * one it could, and one the rule permits. Members are found by reflection, so a probe that
     * failed to compile into the test output cannot let its control pass vacuously.
     */
    @Suppress("unused")
    private class BooleanCollectionProbe {
        fun wrapped(flags: List<Boolean>): Int = flags.size
        fun keyed(flags: Map<String, Boolean>): Int = flags.size
        fun nested(flags: List<List<Boolean>>): Int = flags.size
        fun direct(flag: Boolean): Int = if (flag) 1 else 0
        fun permitted(sizes: List<Long>): Int = sizes.size
    }

    /**
     * The same shapes for the pinned String list, plus `lookalike`, which is the reason the match
     * is on a whole type token: `java.lang.StringBuilder` contains `java.lang.String`.
     */
    @Suppress("unused")
    private class StringCollectionProbe {
        fun wrapped(status: List<String>): Int = status.size
        fun keyed(status: Map<String, Long>): Int = status.size
        fun nested(status: List<List<String>>): Int = status.size
        fun direct(status: String): Int = status.length
        fun permitted(sizes: List<Long>): Int = sizes.size
        fun lookalike(builder: StringBuilder): Int = builder.length
    }

    /** The same five shapes for §10.4's doors, stated over return types because the rule is. */
    @Suppress("unused")
    private class EvidenceDoorProbe {
        fun wrapped(): List<DeliveryEvidence> = emptyList()
        fun keyed(): Map<String, ServedBytesVerified> = emptyMap()
        fun nested(): List<List<DeliveryEvidence>> = emptyList()
        fun direct(verified: ServedBytesVerified): ServedBytesVerified = verified
        fun permitted(): List<String> = emptyList()
    }
}
