package dev.eryalabs.nenya.wire

import java.io.File
import java.lang.reflect.Constructor
import java.lang.reflect.Executable
import java.lang.reflect.Method
import java.lang.reflect.Modifier
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * The structural half of §4.1's ordering rule, enforced by reflection rather than by review.
 *
 * §4.1 says an implementation MUST reject a received event whose `id` does not match its
 * recomputed value **before any other processing**, and the way to enforce an ordering is to make
 * the later step take a type only the earlier step can produce. A code review can assert that
 * today's code does that; this file asserts it about whatever is in the package tomorrow, which
 * is when somebody adds a second factory handing out a [CheckedEvent], or
 * `checkEventId(..., trustTheRelay: Boolean)`.
 *
 * The sweep is the one `PaymentStructureTest` specifies, over `dev/eryalabs/nenya/wire`, and
 * every note there applies here:
 *
 * - **`java.lang.reflect` only.** `kotlin-reflect` is not on any classpath and STOP RULE 11
 *   forbids adding one. `KClass.members` and `KClass.constructors` compile and then throw
 *   `KotlinReflectionNotSupportedError`; `kotlin.reflect.full.*` does not compile at all.
 * - **`getResources`, plural.** The singular form resolves to the **test** output directory,
 *   because `build/classes/kotlin/test` precedes `build/classes/kotlin/main` on the test runtime
 *   classpath and this repo mirrors package names into its test tree. A sweep built on it would
 *   enumerate this very file's class, never see [CheckedEvent], and pass with the implementation
 *   entirely absent.
 * - **Classes asserted by name.** A count is satisfied by whatever the wrong classpath entry
 *   happened to contain, which is exactly the failure the plural form exists to avoid.
 *
 * One finding of this sweep is worth recording, because it is invisible from Kotlin: an
 * `internal` top-level function compiles to a **public** static method on its file's facade
 * class, so `WireEventKt.readEventIdHex` was published API until it was marked `@JvmSynthetic`.
 * The pinned-`String` equality below is what caught it. That is also why the executable filter
 * drops synthetic members: after the annotation the JVM agrees with Kotlin about what is API.
 */
class WireStructureTest {

    private companion object {

        const val PACKAGE: String = "dev.eryalabs.nenya.wire"

        /** The classes this sweep is *about*, by name rather than by count. */
        val EXPECTED_BY_NAME: Set<String> = setOf(
            "WireEvent",
            "EventId",
            "CheckedEvent",
            "WireLimits",
            "WireRejection",
            "WireException",
        )

        /**
         * Every place on the published surface where a `String` may be a parameter, pinned by
         * name. A new one turns this red and forces a human to say why it is not a relay's status
         * string being smuggled in as evidence that an event is genuine. Each of these is either
         * §4.3 hex, an event field §4.1 defines as a string, a diagnostic message, or a
         * compiler-generated enum lookup.
         */
        val STRING_PARAMETERS_PERMITTED: Set<String> = setOf(
            "WireEvent.<init>",                 // the pubkey hex and the content
            "EventId\$Companion.ofHex",         // §4.3 hex, 64 characters, either case
            "CheckedEvent\$Companion.checkEventId", // the claimed id, as the relay sent it
            "WireException.<init>",             // the human-readable rejection message
            "WireRejection.valueOf",            // generated by the Kotlin compiler for enums
        )

        fun mainClasses(): List<Class<*>> {
            val loader = WireStructureTest::class.java.classLoader
            val urls = loader.getResources(PACKAGE.replace('.', '/')).toList()
            val main = urls.firstOrNull { it.path.contains("/classes/kotlin/main/") }
                ?: fail(
                    "no /classes/kotlin/main/ URL for $PACKAGE among $urls — the sweep would " +
                        "otherwise enumerate the test output directory and pass with no implementation",
                )
            val directory = File(main.toURI())
            val files = directory.listFiles { file: File -> file.name.endsWith(".class") }
                ?: fail("${directory.absolutePath} is not a readable directory")
            assertTrue(files.isNotEmpty(), "${directory.absolutePath} holds no classes")
            return files.map { Class.forName("$PACKAGE.${it.name.removeSuffix(".class")}", false, loader) }
        }

        fun publishedClasses(): List<Class<*>> =
            mainClasses().filter { Modifier.isPublic(it.modifiers) && !it.isSynthetic }

        /** Constructors and own public methods, minus everything a client cannot name. */
        fun publishedExecutables(type: Class<*>): List<Executable> =
            type.constructors.toList() +
                type.methods.filter {
                    it.declaringClass == type && !it.isSynthetic && !it.isBridge && '$' !in it.name
                }

        fun label(type: Class<*>, executable: Executable): String {
            val simple = type.name.removePrefix("$PACKAGE.")
            val member = if (executable is Constructor<*>) "<init>" else executable.name
            return "$simple.$member"
        }

        fun wireType(name: String): Class<*> = mainClasses().single { it.name == "$PACKAGE.$name" }
    }

    @Test
    fun `the sweep finds the classes it is about, by name`() {
        val found = mainClasses().map { it.name.removePrefix("$PACKAGE.") }.toSet()

        for (expected in EXPECTED_BY_NAME) {
            assertTrue(
                expected in found,
                "$expected was not among the main classes of $PACKAGE; found $found",
            )
        }
    }

    @Test
    fun `the checked event has no constructor for a client to reach`() {
        val type = wireType("CheckedEvent")

        assertTrue(type.isInterface, "an interface has no constructor to synthesise for")
        assertEquals(
            0,
            type.constructors.size,
            "a private constructor plus a companion factory emits a *public synthetic* constructor " +
                "with a trailing DefaultConstructorMarker, which a Java client can call with null",
        )
        assertTrue(
            type.declaredConstructors.none { it.isSynthetic },
            "not even a synthetic constructor may exist",
        )
        assertTrue(
            type.isSealed,
            "the JVM PermittedSubclasses attribute is what stops another module implementing this " +
                "interface; it is emitted only from JDK 17 upward, so a toolchain drop would " +
                "silently remove it while every other assertion here stayed green",
        )
    }

    @Test
    fun `every implementation of the checked event is non-public`() {
        val type = wireType("CheckedEvent")
        val implementations = mainClasses().filter { it != type && type.isAssignableFrom(it) }

        assertTrue(
            implementations.isNotEmpty(),
            "the sweep must actually find an implementation; the assertions above are true of any " +
                "interface at all and would pass over a public one",
        )
        for (implementation in implementations) {
            assertFalse(
                Modifier.isPublic(implementation.modifiers),
                "${implementation.name} implements CheckedEvent and is JVM-public, so a client can " +
                    "declare an event id-checked that this library never hashed",
            )
        }
    }

    @Test
    fun `no published constructor or method accepts a Boolean`() {
        // Its own by-name guard rather than only the `inspected` floor below. Every other test here
        // would turn red if `mainClasses()` started resolving to the test output directory; this one
        // would not, because the test tree alone satisfies a bare member count.
        val published = publishedClasses()
        val found = published.map { it.name.removePrefix("$PACKAGE.") }.toSet()
        assertTrue(
            EXPECTED_BY_NAME.all { it in found },
            "the Boolean sweep must be looking at $EXPECTED_BY_NAME, not at whatever classpath entry " +
                "it happened to land on; it found $found",
        )

        var inspected = 0
        for (type in published) {
            for (executable in publishedExecutables(type)) {
                inspected++
                for (parameter in executable.parameterTypes) {
                    assertFalse(
                        parameter == java.lang.Boolean.TYPE || parameter == java.lang.Boolean::class.java,
                        "${label(type, executable)} takes a Boolean. §4.1 requires an implementation " +
                            "compute the id itself; a function that can be told the answer is not a " +
                            "computation, and a relay's say-so is not evidence of anything.",
                    )
                }
            }
        }
        assertTrue(inspected > 10, "the sweep inspected only $inspected members, which is not the package")
    }

    @Test
    fun `every published String parameter is on the pinned list`() {
        val found = mutableSetOf<String>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                if (executable.parameterTypes.any { it == String::class.java }) {
                    found += label(type, executable)
                }
            }
        }

        assertEquals(
            STRING_PARAMETERS_PERMITTED,
            found,
            "the set of published members taking a String must match the pinned list exactly. A new " +
                "entry may be a status string arriving as evidence that an event is genuine; a " +
                "missing entry means the sweep stopped seeing the package.",
        )
    }

    @Test
    fun `there is exactly one door into a checked event`() {
        val doors = mutableListOf<String>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                val returned = (executable as? Method)?.returnType ?: continue
                if (returned.name == "$PACKAGE.CheckedEvent") doors += label(type, executable)
            }
        }

        assertEquals(
            listOf("CheckedEvent\$Companion.checkEventId"),
            doors,
            "§4.1's ordering is only as strong as the narrowest door: a second published function " +
                "returning a CheckedEvent is a second way to reach every decoder T9, T10 and T11 " +
                "build on top of it",
        )
    }

    @Test
    fun `the id check takes the claim, the event and the bounds, and nothing that can assert`() {
        val companion = wireType("CheckedEvent\$Companion")
        val check = companion.methods.single { it.name == "checkEventId" }

        assertEquals(
            listOf(String::class.java, WireEvent::class.java, WireLimits::class.java),
            check.parameterTypes.toList(),
            "the claimed id, the event and §4.3's bounds. Anything else on this parameter list is " +
                "something a relay or a counterparty could say.",
        )
        assertEquals(CheckedEvent::class.java, check.returnType)
    }

    /**
     * The trap the payment package fell into and had to be pulled back out of: the sealed
     * interface protects the *checked* type and does nothing for the value types it holds.
     * [EventId] uses the private-constructor-plus-companion-factory idiom, which emits a
     * JVM-public synthetic constructor with a trailing `DefaultConstructorMarker` — so a Java
     * client can write `new EventId(threeBytes, null)` and hold a 3-byte "event id" that §4.3
     * says must have been refused. The invariant therefore lives in `init`, which that
     * constructor also runs, and this test is what proves it does.
     */
    @Test
    fun `the synthetic constructor of EventId still enforces the length`() {
        val type = wireType("EventId")
        val synthetic = type.declaredConstructors.single { it.parameterTypes.size == 2 }
        synthetic.isAccessible = true

        val thrown = assertFailsWith<java.lang.reflect.InvocationTargetException> {
            synthetic.newInstance(ByteArray(3), null)
        }
        val cause = thrown.cause
        assertTrue(cause is WireException, "expected a WireException, got $cause")
        assertEquals(
            WireRejection.WRONG_LENGTH,
            cause.reason,
            "§4.3 requires rejecting a value of the wrong length rather than padding or truncating " +
                "it, on every construction path and not only on the one Kotlin call sites use",
        )
    }

    @Test
    fun `the synthetic constructor of EventId copies the caller's array on the way in`() {
        val type = wireType("EventId")
        val synthetic = type.declaredConstructors.single { it.parameterTypes.size == 2 }
        synthetic.isAccessible = true
        val caller = WireFixtures.sha256("anything".toByteArray())

        val id = synthetic.newInstance(caller, null) as EventId
        val before = id.toHex()
        caller.fill(0)

        assertEquals(
            before,
            id.toHex(),
            "the caller of that constructor keeps its own reference, so an id that did not copy on " +
                "the way in could be rewritten after it was checked",
        )
    }
}
