package dev.eryalabs.nenya.js

import dev.eryalabs.nenya.bid.Bid
import dev.eryalabs.nenya.bid.BidFixtures
import dev.eryalabs.nenya.channel.RumorWriter
import dev.eryalabs.nenya.channel.RumorWriterFixtures
import dev.eryalabs.nenya.listing.AuthoredListing
import dev.eryalabs.nenya.listing.Listing
import dev.eryalabs.nenya.listing.ListingBuild
import dev.eryalabs.nenya.listing.ListingStatus
import dev.eryalabs.nenya.listing.ListingStatusCodec
import dev.eryalabs.nenya.listing.ListingWriter
import dev.eryalabs.nenya.listing.ListingWriterFixtures
import dev.eryalabs.nenya.order.OrderState
import dev.eryalabs.nenya.order.OrderStatusCodec
import dev.eryalabs.nenya.payment.Payee
import dev.eryalabs.nenya.seam.OrderId
import dev.eryalabs.nenya.settlement.PaymentWriter
import dev.eryalabs.nenya.tag.ItemRef
import dev.eryalabs.nenya.tag.NenyaKind
import dev.eryalabs.nenya.tag.TagFixtures
import dev.eryalabs.nenya.wire.CheckedEvent
import dev.eryalabs.nenya.wire.EventId
import dev.eryalabs.nenya.wire.WireEvent
import kotlin.js.JsName
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * T42's proof: for each of the thirteen exported entry points, the facade's answer is the answer the
 * underlying library call gives for the same input — over a corpus, including every refusal the
 * corpus reaches.
 *
 * ### What this is for
 *
 * Decision **P** says the JavaScript layer adds no rule and relaxes none, and T42 says the facade
 * performs no check of its own. Those are claims about behaviour, so they are proved by behaviour: for
 * every case two calls are made — one through `dev.eryalabs.nenya.js` and one straight at
 * `ListingWriter` / `RumorWriter` / `PaymentWriter` / `Listing.decode` / `Bid.decode` — and the two
 * answers must agree down to §4.1's canonical object form, which carries the recomputed `id`.
 *
 * A translation layer that re-implemented a check would be the divergence STOP RULE 5 exists to
 * prevent, and it would show here as one side accepting what the other refused.
 *
 * ### Why both sides are not the same code
 *
 * `JsBoundaryFixtures` holds a **second** translation, written from the Kotlin types' published fields
 * rather than borrowed from the facade's own private helpers. See that file's note: feeding the
 * facade's `asAuthoredListing` into `ListingWriter` would have proved the call was made and nothing
 * about the crossing, and the defect this task fixed — §8.1's `Stated(0)` crossing as `Absent`, so a
 * `["fee", "0"]` listing lost the tag and changed its own id — lived in exactly that gap.
 *
 * ### In `commonTest`, so it runs on JavaScript
 *
 * This is the half of the library that exists *for* JavaScript, and the scheduled webtest job runs
 * every common test as JavaScript on each new commit. A JVM-only proof of a JavaScript facade would be
 * the one place a JVM-only test proves least.
 */
class JsFacadeEqualityTest {

    private companion object {

        /**
         * Listing cases, each built through **all three** of §5.1's and §5.2's entry points.
         *
         * Every case through every kind rather than one kind each, and the extra coverage is the
         * refusals: `ListingWriterFixtures` draws a `status` from the vocabulary of the kind it
         * generated for, so re-reading that token under a different kind reaches §5.2's
         * `UNKNOWN_IS_NOT_EMITTABLE` and §5.2's `alt` requirement from both sides. A refusal the two
         * sides must spell identically is as much of this proof as a built event.
         */
        const val LISTING_CASES: Int = 120

        /** §7.4's eight shapes, cycled, so each of the eight writers sees 30 cases. */
        const val RUMOR_CASES: Int = 240

        /** Legal §6 bids, for the `decodeBid` corpus. */
        const val BID_CASES: Int = 90

        /** Built listings serialised and fed back through `decodeListing`. */
        const val DECODE_CASES: Int = 120

        /** One seeded run, shared by the eight per-shape sweeps rather than regenerated by each. */
        val RUMORS: List<RumorWriterFixtures.Case> = RumorWriterFixtures.cases(RUMOR_CASES)

        /** §5.1's and §5.2's three kinds, in the order the sweep walks them. */
        val LISTING_KINDS: List<Int> = listOf(NenyaKind.REQUEST, NenyaKind.OFFER, NenyaKind.OFFER_DRAFT)

        /**
         * [listing] as the same values read for [kind].
         *
         * Only `status` changes, and it has to: §5.1's and §5.2's vocabularies differ, so the token a
         * case carries means a different `ListingStatus` — or none — under another kind. Read through
         * `ListingStatusCodec.read`, which is the call the facade makes for the same token, because
         * the question here is whether the two *crossings* agree and not whether the codec is right.
         */
        fun asKind(listing: AuthoredListing, kind: Int): AuthoredListing = AuthoredListing(
            authorPubkey = listing.authorPubkey,
            createdAt = listing.createdAt,
            dValue = listing.dValue,
            title = listing.title,
            price = listing.price,
            content = listing.content,
            summary = listing.summary,
            publishedAt = listing.publishedAt,
            status = listing.status?.token?.let { ListingStatusCodec.read(it, kind) },
            mimeType = listing.mimeType,
            topics = listing.topics,
            images = listing.images,
            expiration = listing.expiration,
            alt = listing.alt,
            nenyaVersion = listing.nenyaVersion,
            pubkeyRefs = listing.pubkeyRefs,
            fee = listing.fee,
            feeRecipient = listing.feeRecipient,
            license = listing.license,
            deliverBy = listing.deliverBy,
            extraTags = listing.extraTags,
        )
    }

    // -----------------------------------------------------------------------------------------
    // The three listing builders.
    // -----------------------------------------------------------------------------------------

    /**
     * §5.2's `kind:30404`, §5.1's `kind:30402` and §5.1's `kind:30403`: each crossing's answer is the
     * answer `ListingWriter`'s own entry point gives for the same listing.
     *
     * The three are swept together because the body is one comparison, and each is called **by name**
     * in the `when` below rather than through a function reference, so the published function under
     * test is visible at the call site. The per-kind counts are asserted at the end, so a routing bug
     * that sent every call to one writer cannot pass: the three kinds would stop appearing.
     */
    @Test
    @JsName("the_three_listing_builders_answer_what_ListingWriter_answers")
    fun `the three listing builders answer what ListingWriter answers`() {
        val cases = ListingWriterFixtures.cases(LISTING_CASES)
        assertEquals(LISTING_CASES, cases.size, "the corpus is not the size this test is about")

        var built = 0
        var refused = 0
        val kindsBuilt = mutableSetOf<Int>()
        for (case in cases) {
            val crossed = JsBoundaryFixtures.crossed(case.listing)
            for (kind in LISTING_KINDS) {
                val what = "listing #${case.index} as kind $kind"
                val answer = when (kind) {
                    NenyaKind.REQUEST -> buildListingRequest(crossed)
                    NenyaKind.OFFER -> buildListingOffer(crossed)
                    else -> buildListingDraft(crossed)
                }
                // Through `answerOfCall`, because §5.1's closed `status` vocabulary refuses one of
                // §5.2's request tokens by **throwing** from `ListingStatusCodec.read`, before any
                // writer is reached. That is a refusal the boundary has to return, and comparing
                // only `ListingBuild` values would have let it escape unnoticed.
                val expected = JsBoundaryFixtures.answerOfCall {
                    JsBoundaryFixtures.answerOf(ListingWriterFixtures.build(kind, asKind(case.listing, kind)))
                }
                JsBoundaryFixtures.assertSameAnswer(answer, expected, what)
                if (expected.ok) {
                    built++
                    kindsBuilt += expected.event?.kind ?: fail("$what: a built answer with no event")
                } else {
                    refused++
                }
            }
        }

        // Non-vacuity: a corpus the writer refused everywhere, or accepted everywhere, would leave one
        // half of every comparison above unreachable.
        assertTrue(built > 100, "only $built of the ${cases.size * 3} crossings built an event")
        assertTrue(refused > 0, "no crossing was refused, so the refusal half of the equality is untested")
        assertEquals(
            LISTING_KINDS.toSet(),
            kindsBuilt,
            "the three entry points must emit §5.1's and §5.2's three kinds; a routing bug that sent " +
                "every call to one writer would show up here and nowhere else",
        )
    }

    /**
     * §5.1's two `status` refusals, each reached through the boundary and each named.
     *
     * The sweep above proves the two sides *agree* about refusals. This proves the refusals they agree
     * about are real §5.1 ones and names both reasons, so "they agree" cannot be satisfied by two sides
     * that both refuse everything for the same uninteresting reason. They are different rules reached
     * at different points, and the first is the one that caught a defect:
     *
     * - **One of §5.2's request tokens on an offer** is `STATUS_OUTSIDE_VOCABULARY`, raised by
     *   `ListingStatusCodec.read` **during the translation**, before `ListingWriter` is called. A JVM
     *   caller gets an exception; decision **P** says the boundary returns it, and it did not —
     *   `jsBuild`'s catch list had no arm for `ListingException` until this test was written.
     * - **A token §5.1 and §5.2 both lack** reads as `UNKNOWN` and is refused by the *writer* as
     *   `UNKNOWN_IS_NOT_EMITTABLE`, which is the path that already worked.
     *
     * The first token is derived from the difference between §5.2's and §5.1's own vocabularies rather
     * than typed, so a revision that moved a status between them cannot leave this control testing
     * nothing.
     */
    @Test
    @JsName("both_section_5_1_status_refusals_are_returned_as_values_on_both_sides")
    fun `both section 5 1 status refusals are returned as values on both sides`() {
        val requestOnly = ListingStatusCodec.vocabulary(NenyaKind.REQUEST) -
            ListingStatusCodec.vocabulary(NenyaKind.OFFER)
        val requestToken = requestOnly.firstNotNullOfOrNull { it.token }
            ?: fail("§5.2's request vocabulary no longer holds a status §5.1's offer vocabulary lacks")
        val invented = "part-exchanged"
        assertEquals(
            ListingStatus.UNKNOWN,
            ListingStatusCodec.read(invented, NenyaKind.OFFER),
            "this control needs a token neither §5.1 nor §5.2 names",
        )

        val base = ListingWriterFixtures.minimal(NenyaKind.OFFER)
        fun crossedWith(token: String): JsAuthoredListing = JsAuthoredListing(
            authorPubkey = base.authorPubkey,
            createdAtSeconds = JsBoundaryFixtures.decimal(base.createdAt),
            dValue = base.dValue,
            title = base.title,
            priceMsat = JsBoundaryFixtures.decimal(base.price.millisatoshis),
            statusToken = token,
            alt = base.alt,
        )
        fun libraryAnswerFor(token: String): JsBoundaryFixtures.Answer =
            JsBoundaryFixtures.answerOfCall {
                JsBoundaryFixtures.answerOf(
                    ListingWriter.offer(
                        AuthoredListing(
                            authorPubkey = base.authorPubkey,
                            createdAt = base.createdAt,
                            dValue = base.dValue,
                            title = base.title,
                            price = base.price,
                            status = ListingStatusCodec.read(token, NenyaKind.OFFER),
                            alt = base.alt,
                        ),
                    ),
                )
            }

        val outside = buildListingOffer(crossedWith(requestToken))
        JsBoundaryFixtures.assertSameAnswer(
            outside,
            libraryAnswerFor(requestToken),
            "an offer carrying §5.2's `$requestToken`",
        )
        assertFalse(outside.ok, "§5.1's offer vocabulary is closed")
        assertEquals(
            "STATUS_OUTSIDE_VOCABULARY",
            outside.reason,
            "the refusal must be §5.1's own, raised during the translation and **returned** rather " +
                "than thrown past the boundary",
        )
        assertEquals("ListingRejection", outside.reasonVocabulary, "and from §5's vocabulary")

        val unknown = buildListingOffer(crossedWith(invented))
        JsBoundaryFixtures.assertSameAnswer(
            unknown,
            libraryAnswerFor(invented),
            "an offer carrying the invented `$invented`",
        )
        assertFalse(unknown.ok, "§5.2 makes `unknown` a treatment rather than a token")
        assertEquals(
            "UNKNOWN_IS_NOT_EMITTABLE",
            unknown.reason,
            "this one is the writer's refusal, which is a different rule at a different point",
        )
        assertNotEquals(
            outside.reason,
            unknown.reason,
            "the two rules must be told apart; one reason for both would hide which fired",
        )
    }

    // -----------------------------------------------------------------------------------------
    // The six §7.4 channel builders.
    // -----------------------------------------------------------------------------------------

    /**
     * §7.4's `kind:14` chat: the crossing's answer is `RumorWriter.chat`'s.
     *
     * `order` is drawn present and absent by the corpus, which is §7.4's MAY and the half of it that
     * matters: the writer "MUST NOT derive anything from its presence or absence", so a crossing that
     * invented an order id for the absent case would emit a tag the caller never wrote.
     */
    @Test
    @JsName("buildChat_answers_what_RumorWriter_chat_answers")
    fun `buildChat answers what RumorWriter chat answers`() {
        var withOrder = 0
        var withoutOrder = 0
        forEachShape(RumorWriterFixtures.Shape.CHAT) { case ->
            if (case.order == null) withoutOrder++ else withOrder++
            JsBoundaryFixtures.assertSameAnswer(
                buildChat(JsBoundaryFixtures.crossed(case.envelope), case.order?.toHex()),
                JsBoundaryFixtures.answerOf(RumorWriter.chat(case.envelope, case.order)),
                "$case",
            )
        }
        assertTrue(
            withOrder > 0 && withoutOrder > 0,
            "§7.4's MAY must be drawn both ways: $withOrder present, $withoutOrder absent",
        )
    }

    /** §7.5's `kind:16` `type=1` proposal: the crossing's answer is `RumorWriter.proposal`'s. */
    @Test
    @JsName("buildProposal_answers_what_RumorWriter_proposal_answers")
    fun `buildProposal answers what RumorWriter proposal answers`() {
        var withAmountSat = 0
        forEachShape(RumorWriterFixtures.Shape.PROPOSAL) { case ->
            val terms = case.terms ?: fail("$case must carry terms")
            if (case.amountSat != null) withAmountSat++
            JsBoundaryFixtures.assertSameAnswer(
                buildProposal(
                    envelope = JsBoundaryFixtures.crossed(case.envelope),
                    orderIdHex = requireOrderHex(case),
                    itemCoordinate = requireItemCoordinate(case),
                    terms = JsBoundaryFixtures.crossed(terms),
                    feeRecipient = case.feeRecipient,
                    amountSat = JsBoundaryFixtures.decimalOrNull(case.amountSat),
                ),
                JsBoundaryFixtures.answerOf(
                    RumorWriter.proposal(
                        case.envelope,
                        requireOrder(case),
                        requireItem(case),
                        terms,
                        case.feeRecipient,
                        case.amountSat,
                    ),
                ),
                "$case",
            )
        }
        // §7.5's compatibility tag crosses as a decimal string too, so the corpus has to carry it.
        assertTrue(withAmountSat > 0, "§7.5's `amount` was never drawn, so its crossing is untested")
    }

    /** §11.1's `kind:16` `type=3` status update: the crossing's answer is `RumorWriter.statusUpdate`'s. */
    @Test
    @JsName("buildStatusUpdate_answers_what_RumorWriter_statusUpdate_answers")
    fun `buildStatusUpdate answers what RumorWriter statusUpdate answers`() {
        val statesSeen = mutableSetOf<String>()
        forEachShape(RumorWriterFixtures.Shape.ORDER_UPDATE) { case ->
            val status = case.status ?: fail("$case must carry §11.1's status")
            val token = status.token ?: fail("$case carries §11.1's `unknown`, which has no token")
            statesSeen += token
            JsBoundaryFixtures.assertSameAnswer(
                buildStatusUpdate(
                    envelope = JsBoundaryFixtures.crossed(case.envelope),
                    orderIdHex = requireOrderHex(case),
                    statusToken = token,
                    itemCoordinate = case.item?.coordinate?.toTagValue(),
                    terms = case.terms?.let { JsBoundaryFixtures.crossed(it) },
                    feeRecipient = case.feeRecipient,
                ),
                JsBoundaryFixtures.answerOf(
                    RumorWriter.statusUpdate(
                        case.envelope,
                        requireOrder(case),
                        status,
                        case.item,
                        case.terms,
                        case.feeRecipient,
                    ),
                ),
                "$case",
            )
        }
        assertTrue(
            statesSeen.size > 3,
            "only $statesSeen reached the crossing; §11.1's emittable vocabulary is wider than that",
        )
    }

    /**
     * A `status` token §11.1 has no rule for reaches the **writer's** refusal, not the crossing's.
     *
     * `OrderStatusCodec.read` never throws — §11.1 makes an unrecognised status a fact about the
     * counterparty rather than a malformed input — so the crossing hands `UNKNOWN` to the writer and
     * the writer refuses it. That is the discipline under test: the crossing restates no vocabulary,
     * and the assertion on [JsCrossing.VOCABULARY] is what says so.
     */
    @Test
    @JsName("an_unknown_status_token_reaches_the_writers_own_refusal_on_both_sides")
    fun `an unknown status token reaches the writer's own refusal on both sides`() {
        val case = RUMORS.first { it.shape == RumorWriterFixtures.Shape.ORDER_UPDATE }
        val invented = "part-exchanged"
        assertEquals(
            OrderState.UNKNOWN,
            OrderStatusCodec.read(invented),
            "this control needs a token §11.1 has no rule for",
        )

        val answer = buildStatusUpdate(
            envelope = JsBoundaryFixtures.crossed(case.envelope),
            orderIdHex = requireOrderHex(case),
            statusToken = invented,
            itemCoordinate = case.item?.coordinate?.toTagValue(),
            terms = case.terms?.let { JsBoundaryFixtures.crossed(it) },
            feeRecipient = case.feeRecipient,
        )
        val expected = JsBoundaryFixtures.answerOf(
            RumorWriter.statusUpdate(
                case.envelope,
                requireOrder(case),
                OrderState.UNKNOWN,
                case.item,
                case.terms,
                case.feeRecipient,
            ),
        )

        JsBoundaryFixtures.assertSameAnswer(answer, expected, "a status update carrying `$invented`")
        assertFalse(answer.ok, "§11.1's `unknown` is a treatment rather than a token")
        assertNotEquals(
            JsCrossing.VOCABULARY,
            answer.reasonVocabulary,
            "the refusal must come from the writer, never from the crossing's own vocabulary",
        )
    }

    /** §10.1's `kind:16` `type=5` commitment: the crossing's answer is `RumorWriter.commitment`'s. */
    @Test
    @JsName("buildCommitment_answers_what_RumorWriter_commitment_answers")
    fun `buildCommitment answers what RumorWriter commitment answers`() {
        forEachShape(RumorWriterFixtures.Shape.COMMITMENT) { case ->
            val commitment = case.commitment ?: fail("$case must carry §10.1's four values")
            val url = case.url ?: fail("$case must carry §10.1's url")
            JsBoundaryFixtures.assertSameAnswer(
                buildCommitment(
                    envelope = JsBoundaryFixtures.crossed(case.envelope),
                    orderIdHex = requireOrderHex(case),
                    commitment = JsBoundaryFixtures.crossed(commitment),
                    url = url,
                ),
                JsBoundaryFixtures.answerOf(
                    RumorWriter.commitment(case.envelope, requireOrder(case), commitment, url),
                ),
                "$case",
            )
        }
    }

    /** §10.3's `kind:15` release: the crossing's answer is `RumorWriter.release`'s. */
    @Test
    @JsName("buildRelease_answers_what_RumorWriter_release_answers")
    fun `buildRelease answers what RumorWriter release answers`() {
        var withFileType = 0
        var withoutFileType = 0
        forEachShape(RumorWriterFixtures.Shape.RELEASE) { case ->
            val release = case.release ?: fail("$case must carry a release")
            val key = case.decryptionKey ?: fail("$case must carry §10.2's key")
            val nonce = case.decryptionNonce ?: fail("$case must carry §10.2's nonce")
            if (release.fileType == null) withoutFileType++ else withFileType++
            JsBoundaryFixtures.assertSameAnswer(
                buildRelease(
                    envelope = JsBoundaryFixtures.crossed(case.envelope),
                    orderIdHex = requireOrderHex(case),
                    release = JsBoundaryFixtures.crossed(release),
                    decryptionKeyHex = key,
                    decryptionNonceHex = nonce,
                ),
                JsBoundaryFixtures.answerOf(
                    RumorWriter.release(case.envelope, requireOrder(case), release, key, nonce),
                ),
                "$case",
            )
        }
        // §10.3 makes an absent `file-type` reach the identity check rather than the decoder, so the
        // corpus has to carry it absent — and a nullable field that is never null is not tested.
        assertTrue(
            withFileType > 0 && withoutFileType > 0,
            "§10.3's `file-type` must cross present and absent: $withFileType/$withoutFileType",
        )
    }

    /** §6.1's `kind:16` `type=6` private bid: the crossing's answer is `RumorWriter.privateBid`'s. */
    @Test
    @JsName("buildPrivateBid_answers_what_RumorWriter_privateBid_answers")
    fun `buildPrivateBid answers what RumorWriter privateBid answers`() {
        forEachShape(RumorWriterFixtures.Shape.PRIVATE_BID) { case ->
            val terms = case.terms ?: fail("$case must carry §6.1's terms")
            JsBoundaryFixtures.assertSameAnswer(
                buildPrivateBid(
                    envelope = JsBoundaryFixtures.crossed(case.envelope),
                    itemCoordinate = requireItemCoordinate(case),
                    terms = JsBoundaryFixtures.crossed(terms),
                    feeRecipient = case.feeRecipient,
                ),
                JsBoundaryFixtures.answerOf(
                    RumorWriter.privateBid(case.envelope, requireItem(case), terms, case.feeRecipient),
                ),
                "$case",
            )
        }
    }

    // -----------------------------------------------------------------------------------------
    // The two settlement builders.
    // -----------------------------------------------------------------------------------------

    /** §8.6's `kind:16` `type=2` payment request: the crossing's answer is `PaymentWriter`'s. */
    @Test
    @JsName("buildPaymentRequest_answers_what_PaymentWriter_paymentRequest_answers")
    fun `buildPaymentRequest answers what PaymentWriter paymentRequest answers`() {
        val payeesSeen = mutableSetOf<String>()
        forEachShape(RumorWriterFixtures.Shape.PAYMENT_REQUEST) { case ->
            val payee = case.payee ?: fail("$case must name §8.6's payee")
            val invoice = case.invoice ?: fail("$case must carry §8.6's invoice")
            val medium = case.medium.token ?: fail("$case carries a medium §9.4 gives no token")
            payeesSeen += payee.token
            JsBoundaryFixtures.assertSameAnswer(
                buildPaymentRequest(
                    envelope = JsBoundaryFixtures.crossed(case.envelope),
                    orderIdHex = requireOrderHex(case),
                    payeeToken = payee.token,
                    invoice = invoice.text,
                    feeRecipient = case.feeRecipient,
                    mediumToken = medium,
                    terms = case.terms?.let { JsBoundaryFixtures.crossed(it) },
                ),
                JsBoundaryFixtures.answerOf(
                    PaymentWriter.paymentRequest(
                        case.envelope,
                        requireOrder(case),
                        payee,
                        invoice,
                        case.feeRecipient,
                        case.medium,
                        case.terms,
                    ),
                ),
                "$case",
            )
        }
        assertEquals(
            Payee.entries.map { it.token }.toSet(),
            payeesSeen,
            "§8.6's two payees must both cross; only $payeesSeen did",
        )
    }

    /** §9.2's `kind:17` receipt: the crossing's answer is `PaymentWriter.receipt`'s. */
    @Test
    @JsName("buildReceipt_answers_what_PaymentWriter_receipt_answers")
    fun `buildReceipt answers what PaymentWriter receipt answers`() {
        val mediaSeen = mutableSetOf<String>()
        forEachShape(RumorWriterFixtures.Shape.RECEIPT) { case ->
            val payee = case.payee ?: fail("$case must name §8.6's payee")
            val reference = case.reference ?: fail("$case must carry §9.2's reference")
            val proof = case.proof ?: fail("$case must carry §9.2's proof")
            val medium = case.medium.token ?: fail("$case carries a medium §9.4 gives no token")
            mediaSeen += medium
            JsBoundaryFixtures.assertSameAnswer(
                buildReceipt(
                    envelope = JsBoundaryFixtures.crossed(case.envelope),
                    orderIdHex = requireOrderHex(case),
                    payeeToken = payee.token,
                    reference = reference,
                    proof = proof,
                    feeRecipient = case.feeRecipient,
                    mediumToken = medium,
                    terms = case.terms?.let { JsBoundaryFixtures.crossed(it) },
                ),
                JsBoundaryFixtures.answerOf(
                    PaymentWriter.receipt(
                        case.envelope,
                        requireOrder(case),
                        payee,
                        reference,
                        proof,
                        case.feeRecipient,
                        case.medium,
                        case.terms,
                    ),
                ),
                "$case",
            )
        }
        // §9.4's rails: the one with a verification rule and the two with none. A corpus that crossed
        // only `lightning` would never exercise the rails whose proof is not a preimage.
        assertTrue(mediaSeen.size >= 3, "only $mediaSeen reached the crossing; §9.4 names more rails")
    }

    // -----------------------------------------------------------------------------------------
    // The two decoders.
    // -----------------------------------------------------------------------------------------

    /**
     * §5.1's and §5.2's decode: `decodeListing` reports the listing `Listing.decode` reports, field by
     * field, and the id check it cannot be reached without.
     *
     * The field comparison is the part a round trip could not reach: a getter that translated the
     * wrong value would still produce an event the writer could rebuild, if the writer read the same
     * wrong value back. Every field `JsListing` publishes is compared, and `JsSurfaceTest` sweeps the
     * compiled class to prove that list is complete rather than merely long.
     */
    @Test
    @JsName("decodeListing_reports_what_Listing_decode_reports")
    fun `decodeListing reports what Listing decode reports`() {
        var compared = 0
        for (case in ListingWriterFixtures.cases(DECODE_CASES)) {
            val event = when (val build = ListingWriterFixtures.build(case.kind, case.listing)) {
                is ListingBuild.Built -> build.event
                is ListingBuild.Refused -> continue
            }
            val what = "listing #${case.index} on kind ${case.kind}"
            val expected = Listing.decode(CheckedEvent.checkEventId(EventId.of(event).toHex(), event))
            val answer = decodeListing(JsBoundaryFixtures.json(event))

            assertTrue(answer.ok, "$what: the crossing refused what the library decoded: ${answer.reason}")
            assertEquals("listing", answer.kind, "$what: `kind` must discriminate with `ok`")
            val crossed = answer.listing ?: fail("$what: an ok answer with no listing")
            JsBoundaryFixtures.assertSameFields(JsBoundaryFixtures.listingFields(crossed, expected), what)
            assertNull(answer.reason, "$what: an ok answer must name no reason")
            compared++
        }
        assertTrue(compared > 100, "only $compared listings reached the decode comparison")
    }

    /** §6's decode: `decodeBid` reports what `Bid.decode` reports, on the same terms. */
    @Test
    @JsName("decodeBid_reports_what_Bid_decode_reports")
    fun `decodeBid reports what Bid decode reports`() {
        var compared = 0
        for (fixture in BidFixtures.bids(BID_CASES)) {
            val event = WireEvent(
                TagFixtures.pubkeyFor(fixture.index),
                BidFixtures.CREATED_AT,
                NenyaKind.PUBLIC_BID,
                fixture.tags,
                fixture.content,
            )
            val what = "bid #${fixture.index} scoped to kind ${fixture.listingKind}"
            val expected = Bid.decode(CheckedEvent.checkEventId(EventId.of(event).toHex(), event))
            val answer = decodeBid(JsBoundaryFixtures.json(event))

            assertTrue(answer.ok, "$what: the crossing refused what the library decoded: ${answer.reason}")
            assertEquals("bid", answer.kind, "$what: `kind` must discriminate with `ok`")
            val crossed = answer.bid ?: fail("$what: an ok answer with no bid")
            JsBoundaryFixtures.assertSameFields(JsBoundaryFixtures.bidFields(crossed, expected), what)
            compared++
        }
        assertTrue(compared > 80, "only $compared bids reached the decode comparison")
    }

    /**
     * Every refusal the two decoders can report comes from the library, named the way the library
     * names it.
     *
     * The positive sweeps above cannot reach these: a corpus of events this library built decodes by
     * construction. Each case here is hostile input of a different shape and each lands on a different
     * arm of the decoders' catch ladders — which is what proves the arms are wired to the right
     * vocabulary rather than all answering the same thing.
     */
    @Test
    @JsName("both_decoders_report_the_librarys_own_refusal_for_hostile_input")
    fun `both decoders report the library's own refusal for hostile input`() {
        val listing = ListingWriterFixtures.built(
            ListingWriterFixtures.build(NenyaKind.OFFER, ListingWriterFixtures.minimal(NenyaKind.OFFER)),
            "the minimal offer",
        )
        val listingJson = JsBoundaryFixtures.json(listing)
        // A second event, so the id substituted below is one this repository computed rather than a
        // hex string somebody typed out (the Definition of done's rule on encoded values).
        val other = ListingWriterFixtures.built(
            ListingWriterFixtures.build(
                NenyaKind.OFFER,
                ListingWriterFixtures.minimal(NenyaKind.OFFER, index = 1),
            ),
            "a second offer",
        )
        val mismatched = listingJson.replace(EventId.of(listing).toHex(), EventId.of(other).toHex())
        assertNotEquals(listingJson, mismatched, "the id-mismatch case must actually differ")

        val bidEvent = WireEvent(
            TagFixtures.pubkeyFor(0),
            BidFixtures.CREATED_AT,
            NenyaKind.PUBLIC_BID,
            BidFixtures.minimalBid(),
            "",
        )
        val bidJson = JsBoundaryFixtures.json(bidEvent)

        val vocabularies = mutableSetOf<String>()

        // §4.3's JSON rules, before any §5 or §6 rule runs.
        for (hostile in listOf("", "not an event", "{\"id\":")) {
            val answer = decodeListing(hostile)
            assertFalse(answer.ok, "`$hostile` is not an event object")
            assertEquals(
                "JsonRejection",
                answer.reasonVocabulary,
                "§4.3's JSON rules refuse this one, and the crossing must say so",
            )
            vocabularies += "JsonRejection"
        }

        // §4.1's id check, which the decoder cannot be reached without.
        val idAnswer = decodeListing(mismatched)
        assertFalse(idAnswer.ok, "an event whose id is not the hash of its own fields must be refused")
        assertEquals("WireRejection", idAnswer.reasonVocabulary, "§4.1's id check owns this refusal")
        assertEquals("ID_MISMATCH", idAnswer.reason, "and names the rule it broke")
        vocabularies += "WireRejection"

        // §6's bid fed to §5's decoder, and the reverse: each decoder's own kind check.
        val notAListing = decodeListing(bidJson)
        assertFalse(notAListing.ok, "a kind:1111 bid is not a listing")
        assertEquals("ListingRejection", notAListing.reasonVocabulary, "§5's decoder owns this refusal")
        vocabularies += "ListingRejection"

        val notABid = decodeBid(listingJson)
        assertFalse(notABid.ok, "a kind:30402 offer is not a bid")
        assertEquals("BidRejection", notABid.reasonVocabulary, "§6's decoder owns this refusal")
        vocabularies += "BidRejection"

        // The two positive controls, so "everything is refused" cannot satisfy this test.
        assertTrue(decodeListing(listingJson).ok, "the minimal offer must still decode")
        assertTrue(decodeBid(bidJson).ok, "the minimal bid must still decode")

        assertEquals(
            setOf("JsonRejection", "WireRejection", "ListingRejection", "BidRejection"),
            vocabularies,
            "four different arms of the two decoders' catch ladders must have been reached",
        )
        assertFalse(
            JsCrossing.VOCABULARY in vocabularies,
            "not one of these refusals may come from the crossing's own vocabulary: a decoder that " +
                "answered `${JsCrossing.VOCABULARY}` would be deciding a §4, §5 or §6 question itself",
        )
    }

    // -----------------------------------------------------------------------------------------
    // Helpers.
    // -----------------------------------------------------------------------------------------

    /** Every corpus case of [shape], with a floor so a filter that matched nothing cannot pass. */
    private fun forEachShape(
        shape: RumorWriterFixtures.Shape,
        body: (RumorWriterFixtures.Case) -> Unit,
    ) {
        val cases = RUMORS.filter { it.shape == shape }
        assertTrue(
            cases.size >= RUMOR_CASES / RumorWriterFixtures.Shape.entries.size,
            "${cases.size} case(s) of $shape is not the corpus this test is about",
        )
        for (case in cases) body(case)
    }

    private fun requireOrder(case: RumorWriterFixtures.Case): OrderId =
        case.order ?: fail("$case must carry §7.4's order id")

    private fun requireOrderHex(case: RumorWriterFixtures.Case): String = requireOrder(case).toHex()

    private fun requireItem(case: RumorWriterFixtures.Case): ItemRef =
        case.item ?: fail("$case must carry §5.3's item")

    private fun requireItemCoordinate(case: RumorWriterFixtures.Case): String =
        requireItem(case).coordinate.toTagValue()
}
