package dev.eryalabs.nenya.listing

import java.io.File
import java.lang.reflect.Constructor
import java.lang.reflect.Executable
import java.lang.reflect.Method
import java.lang.reflect.Modifier
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * The round's headline rule — no `Boolean` and no status-shaped `String` as evidence — reaching
 * this package, and §11.1's "one codec MUST NOT serve both" made structural.
 *
 * The sweep is the one `PaymentStructureTest` specifies, over `dev/eryalabs/nenya/listing`, and
 * every note there applies here:
 *
 * - **`java.lang.reflect` only.** `kotlin-reflect` is not on any classpath and STOP RULE 11
 *   forbids adding one. `KClass.members` and `KClass.constructors` compile and then throw
 *   `KotlinReflectionNotSupportedError`; `kotlin.reflect.full.*` does not compile at all.
 * - **`getResources`, plural.** The singular form resolves to the **test** output directory,
 *   because `build/classes/kotlin/test` precedes `build/classes/kotlin/main` on the test runtime
 *   classpath and this repo mirrors package names into its test tree. A sweep built on it would
 *   enumerate this very file's class, never see [Listing], and pass with the implementation
 *   entirely absent.
 * - **Classes asserted by name.** A count is satisfied by whatever the wrong classpath entry
 *   happened to contain, which is exactly the failure the plural form exists to avoid.
 */
class ListingStructureTest {

    private companion object {

        const val PACKAGE: String = "dev.eryalabs.nenya.listing"

        /** The order package, which nothing here may take, return or extend (§11.1). */
        const val ORDER_PACKAGE: String = "dev.eryalabs.nenya.order"

        /** The classes this sweep is *about*, by name rather than by count. */
        val EXPECTED_BY_NAME: Set<String> = setOf(
            "Listing",
            "ListingActivity",
            "ListingSide",
            "ListingStatus",
            "ListingStatusCodec",
            "ListingRejection",
            "ListingException",
        )

        /**
         * Every place on the published surface where a `String` may be a parameter, pinned by name.
         *
         * A new one turns this red and forces a human to say why it is not a counterparty's status
         * string arriving as evidence of something. Each of these is either a §5.3 tag value the
         * decoder was handed, a §5.1/§5.2 vocabulary token being read, a diagnostic message, or a
         * compiler-generated enum lookup.
         */
        val STRING_PARAMETERS_PERMITTED: Set<String> = setOf(
            "Listing.<init>",                       // the author pubkey, content, title — event fields
            "ListingException.<init>",              // the tag name and the rejection message
            "ListingSide\$Companion.byToken",       // a §5.3 `t` token being read
            "ListingStatusCodec.read",              // the raw `status` token, as the publisher wrote it
            "ListingActivity.valueOf",              // generated by the Kotlin compiler for enums
            "ListingRejection.valueOf",
            "ListingSide.valueOf",
            "ListingStatus.valueOf",
        )

        fun mainClasses(): List<Class<*>> {
            val loader = ListingStructureTest::class.java.classLoader
            val urls = loader.getResources(PACKAGE.replace('.', '/')).toList()
            val main = urls.firstOrNull { it.path.contains("/classes/kotlin/main/") }
                ?: fail(
                    "no /classes/kotlin/main/ URL for $PACKAGE among $urls — the sweep would " +
                        "otherwise enumerate the test output directory and pass with no implementation",
                )
            val directory = File(main.toURI())
            val files = directory.listFiles { file: File -> file.name.endsWith(".class") }
                ?: fail("${directory.absolutePath} is not a readable directory")
            assertTrue(files.isNotEmpty(), "${directory.absolutePath} holds no classes")
            // The class files this package compiled to at commit 6432814, pinned as a floor so a
            // partial output directory after a source-layout move goes red instead of sweeping less.
            val pinned = 14
            assertTrue(
                files.size >= pinned,
                "${directory.absolutePath} holds ${files.size} class file(s); at least $pinned were pinned",
            )
            return files.map { Class.forName("$PACKAGE.${it.name.removeSuffix(".class")}", false, loader) }
        }

        fun publishedClasses(): List<Class<*>> =
            mainClasses().filter { Modifier.isPublic(it.modifiers) && !it.isSynthetic }

        /** Constructors and own public methods, minus everything a client cannot name. */
        fun publishedExecutables(type: Class<*>): List<Executable> =
            type.constructors.toList() +
                type.methods.filter {
                    it.declaringClass == type && !it.isSynthetic && !it.isBridge && '$' !in it.name
                }

        fun label(type: Class<*>, executable: Executable): String {
            val simple = type.name.removePrefix("$PACKAGE.")
            val member = if (executable is Constructor<*>) "<init>" else executable.name
            return "$simple.$member"
        }
    }

    @Test
    fun `the sweep finds the classes it is about, by name`() {
        val found = mainClasses().map { it.name.removePrefix("$PACKAGE.") }.toSet()

        for (expected in EXPECTED_BY_NAME) {
            assertTrue(
                expected in found,
                "$expected was not among the main classes of $PACKAGE; found $found",
            )
        }
    }

    @Test
    fun `no published constructor or method accepts a Boolean`() {
        // Its own by-name guard rather than only the `inspected` floor below: every other test here
        // would turn red if `mainClasses()` started resolving to the test output directory, and this
        // one would not, because the test tree alone satisfies a bare member count.
        val published = publishedClasses()
        val found = published.map { it.name.removePrefix("$PACKAGE.") }.toSet()
        assertTrue(
            EXPECTED_BY_NAME.all { it in found },
            "the Boolean sweep must be looking at $EXPECTED_BY_NAME, not at whatever classpath " +
                "entry it happened to land on; it found $found",
        )

        var inspected = 0
        for (type in published) {
            for (executable in publishedExecutables(type)) {
                inspected++
                for (parameter in executable.parameterTypes) {
                    assertFalse(
                        parameter == java.lang.Boolean.TYPE || parameter == java.lang.Boolean::class.java,
                        "${label(type, executable)} takes a Boolean. A listing is decoded from an " +
                            "event this library hashed for itself; a function that can be told the " +
                            "answer is not a decoder, and a relay's say-so is not evidence of anything.",
                    )
                }
            }
        }
        assertTrue(inspected > 10, "the sweep inspected only $inspected members, which is not the package")
    }

    @Test
    fun `every published String parameter is on the pinned list`() {
        val found = mutableSetOf<String>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                if (executable.parameterTypes.any { it == String::class.java }) {
                    found += label(type, executable)
                }
            }
        }

        assertEquals(
            STRING_PARAMETERS_PERMITTED,
            found,
            "the set of published members taking a String must match the pinned list exactly. A " +
                "new entry may be a status string arriving as evidence; a missing entry means the " +
                "sweep stopped seeing the package.",
        )
    }

    /**
     * §11.1's rule, enforced where an implementer would breach it. A listing status is an
     * announcement to the board and never a transition: "a buyer republishing their request as
     * `fulfilled` is an announcement, not a transition." So no published member of this package
     * may take or return anything from the order package, and no type here may extend one.
     *
     * The direction matters. T6 closed the other one — every listing token lands in
     * `OrderState.UNKNOWN` — and a codec can satisfy that while still handing a caller an
     * `OrderState` derived from a `["status", "cancelled"]` on a listing.
     */
    @Test
    fun `nothing in this package takes, returns or extends an order-package type`() {
        for (type in publishedClasses()) {
            var supertype: Class<*>? = type.superclass
            while (supertype != null) {
                assertFalse(
                    supertype.name.startsWith("$ORDER_PACKAGE."),
                    "${type.name} extends ${supertype.name}",
                )
                supertype = supertype.superclass
            }
            for (implemented in type.interfaces) {
                assertFalse(
                    implemented.name.startsWith("$ORDER_PACKAGE."),
                    "${type.name} implements ${implemented.name}",
                )
            }
            for (executable in publishedExecutables(type)) {
                val mentioned = executable.parameterTypes.toList() +
                    listOfNotNull((executable as? Method)?.returnType)
                for (other in mentioned) {
                    assertFalse(
                        other.name.startsWith("$ORDER_PACKAGE."),
                        "${label(type, executable)} mentions ${other.name}; §11.1 forbids one " +
                            "codec serving the listing vocabulary and the order-state vocabulary, " +
                            "and forbids deriving order state from a listing status at all",
                    )
                }
            }
        }
    }

    /**
     * The narrowest door, as T8 puts it: every published function returning a [Listing] is one an
     * event had to pass §4.1's id check to reach. A second one would be a second way to decode a
     * listing this library never hashed.
     */
    @Test
    fun `the only published function returning a listing is decode`() {
        val doors = mutableListOf<String>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                val returned = (executable as? Method)?.returnType ?: continue
                if (returned.name == "$PACKAGE.Listing") doors += label(type, executable)
            }
        }

        assertEquals(listOf("Listing\$Companion.decode"), doors)
    }

    /** The published constructor `Listing` does carry is the internal one, which is not a door. */
    @Test
    fun `a listing cannot be built from values a caller chose`() {
        val type = publishedClasses().single { it.name == "$PACKAGE.Listing" }

        for (constructor in type.constructors) {
            assertTrue(
                constructor.parameterTypes.any { it.name == "dev.eryalabs.nenya.wire.EventId" },
                "Kotlin publishes an `internal` constructor to the JVM, so this one is reachable " +
                    "from Java — but only with an EventId, which only T8's recomputation produces. " +
                    "A constructor taking loose values would be a listing nobody checked.",
            )
        }
    }
}
