package dev.eryalabs.nenya.wire

import java.io.File
import java.lang.reflect.Constructor
import java.lang.reflect.Executable
import java.lang.reflect.Method
import java.lang.reflect.Modifier
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * The structural half of §4.1's ordering rule, enforced by reflection rather than by review.
 *
 * §4.1 says an implementation MUST reject a received event whose `id` does not match its
 * recomputed value **before any other processing**, and the way to enforce an ordering is to make
 * the later step take a type only the earlier step can produce. A code review can assert that
 * today's code does that; this file asserts it about whatever is in the package tomorrow, which
 * is when somebody adds a second factory handing out a [CheckedEvent], or
 * `checkEventId(..., trustTheRelay: Boolean)`.
 *
 * The sweep is the one `PaymentStructureTest` specifies, over `dev/eryalabs/nenya/wire`, and
 * every note there applies here:
 *
 * - **`java.lang.reflect` only.** `kotlin-reflect` is not on any classpath and STOP RULE 11
 *   forbids adding one. `KClass.members` and `KClass.constructors` compile and then throw
 *   `KotlinReflectionNotSupportedError`; `kotlin.reflect.full.*` does not compile at all.
 * - **`getResources`, plural.** The singular form resolves to the **test** output directory,
 *   because `build/classes/kotlin/jvm/test` precedes `build/classes/kotlin/jvm/main` on the test runtime
 *   classpath and this repo mirrors package names into its test tree. A sweep built on it would
 *   enumerate this very file's class, never see [CheckedEvent], and pass with the implementation
 *   entirely absent.
 * - **Classes asserted by name.** A count is satisfied by whatever the wrong classpath entry
 *   happened to contain, which is exactly the failure the plural form exists to avoid.
 * - **Generic types, not erased ones.** An `Executable`'s plain parameter-type and return-type
 *   arrays report the **erasure**, so `fun tell(flags: List<Boolean>)` reads as plain
 *   `java.util.List` and satisfies "no published member accepts a Boolean", and
 *   `fun all(): List<CheckedEvent>` reads the same way and satisfies "there is exactly one door
 *   into a checked event". Every scan below therefore reads
 *   `genericParameterTypes`/`genericReturnType` and matches whole type tokens inside `typeName`
 *   through [namesType], and each carries a probe beside it — a test-only class holding the
 *   forbidden shape wrapped in a collection — fed to the sweep's **own** predicate, because a
 *   control exercising a second copy of the check proves nothing about the first.
 *
 * One finding of this sweep is worth recording, because it is invisible from Kotlin: an
 * `internal` top-level function compiles to a **public** static method on its file's facade
 * class, so `WireEventKt.readEventIdHex` was published API until it was marked `@JvmSynthetic`.
 * The pinned-`String` equality below is what caught it. That is also why the executable filter
 * drops synthetic members: after the annotation the JVM agrees with Kotlin about what is API.
 */
class WireStructureTest {

    private companion object {

        const val PACKAGE: String = "dev.eryalabs.nenya.wire"

        /** The classes this sweep is *about*, by name rather than by count. */
        val EXPECTED_BY_NAME: Set<String> = setOf(
            "WireEvent",
            "EventId",
            "CheckedEvent",
            "WireLimits",
            "WireRejection",
            "WireException",
            "EventJson",
            "ReadEvent",
            "JsonRejection",
            "JsonException",
        )

        /**
         * Every place on the published surface where a `String` may be a parameter, pinned by
         * name. A new one turns this red and forces a human to say why it is not a relay's status
         * string being smuggled in as evidence that an event is genuine. Each of these is either
         * §4.3 hex, an event field §4.1 defines as a string, a diagnostic message, or a
         * compiler-generated enum lookup.
         */
        val STRING_PARAMETERS_PERMITTED: Set<String> = setOf(
            "WireEvent.<init>",                 // the pubkey hex and the content
            "EventId\$Companion.ofHex",         // §4.3 hex, 64 characters, either case
            "CheckedEvent\$Companion.checkEventId", // the claimed id, as the relay sent it
            "WireException.<init>",             // the human-readable rejection message
            "WireRejection.valueOf",            // generated by the Kotlin compiler for enums
            "EventJson.read",                   // §7.1's object form, as the relay sent it
            "EventJson.writeSigned",            // the `sig` the injected signer produced
            "ReadEvent.<init>",                 // the claimed id and the claimed sig, both claims
            "JsonException.<init>",             // the human-readable rejection message
            "JsonRejection.valueOf",            // generated by the Kotlin compiler for enums
        )

        /** `String` as it appears inside a `typeName`, bare or as a generic's type argument. */
        val STRING_TYPE: String = String::class.java.typeName

        /** The checked type as it appears inside a `typeName`, bare or as a type argument. */
        val CHECKED_EVENT_TYPE: String = "$PACKAGE.CheckedEvent"

        fun mainClasses(): List<Class<*>> {
            val loader = WireStructureTest::class.java.classLoader
            val urls = loader.getResources(PACKAGE.replace('.', '/')).toList()
            val main = urls.firstOrNull { it.path.contains("/classes/kotlin/jvm/main/") }
                ?: fail(
                    "no /classes/kotlin/jvm/main/ URL for $PACKAGE among $urls — the sweep would " +
                        "otherwise enumerate the test output directory and pass with no implementation",
                )
            val directory = File(main.toURI())
            val files = directory.listFiles { file: File -> file.name.endsWith(".class") }
                ?: fail("${directory.absolutePath} is not a readable directory")
            assertTrue(files.isNotEmpty(), "${directory.absolutePath} holds no classes")
            // The class files this package compiled to at commit 6432814, pinned as a floor so a
            // partial output directory after a source-layout move goes red instead of sweeping less.
            val pinned = 12
            assertTrue(
                files.size >= pinned,
                "${directory.absolutePath} holds ${files.size} class file(s); at least $pinned were pinned",
            )
            return files.map { Class.forName("$PACKAGE.${it.name.removeSuffix(".class")}", false, loader) }
        }

        fun publishedClasses(): List<Class<*>> =
            mainClasses().filter { Modifier.isPublic(it.modifiers) && !it.isSynthetic }

        /** Constructors and own public methods, minus everything a client cannot name. */
        fun publishedExecutables(type: Class<*>): List<Executable> =
            type.constructors.toList() +
                type.methods.filter {
                    it.declaringClass == type && !it.isSynthetic && !it.isBridge && '$' !in it.name
                }

        fun label(type: Class<*>, executable: Executable): String {
            val simple = type.name.removePrefix("$PACKAGE.")
            val member = if (executable is Constructor<*>) "<init>" else executable.name
            return "$simple.$member"
        }

        fun wireType(name: String): Class<*> = mainClasses().single { it.name == "$PACKAGE.$name" }

        /**
         * Whether [typeName] names [sought] itself or names it inside a generic's type arguments.
         *
         * A bare `contains` is wrong: `java.lang.StringBuilder` contains `java.lang.String`, and the
         * pinned-`String` sweep below would then report a member that takes no string at all. So the
         * match is on a whole type token — the character either side must not continue an identifier.
         *
         * Declared here rather than borrowed from another package's structure test on purpose: this
         * repository keeps a reflection helper per package, because one shared helper would be a
         * single sweep deciding at run time which package it is about.
         */
        fun namesType(typeName: String, sought: String): Boolean {
            var from = 0
            while (true) {
                val at = typeName.indexOf(sought, from)
                if (at < 0) return false
                val before = if (at == 0) ' ' else typeName[at - 1]
                val afterAt = at + sought.length
                val after = if (afterAt >= typeName.length) ' ' else typeName[afterAt]
                if (!continuesIdentifier(before) && !continuesIdentifier(after)) return true
                from = at + 1
            }
        }

        private fun continuesIdentifier(c: Char): Boolean =
            c.isLetterOrDigit() || c == '.' || c == '$' || c == '_'

        /**
         * The **generic** type names of [executable]'s parameters, in order.
         *
         * `typeName` prints `java.util.List<java.lang.Boolean>` where `parameterTypes` prints
         * `java.util.List`, and that difference is the whole of what the sweeps below gained.
         */
        fun parameterTypeNames(executable: Executable): List<String> =
            executable.genericParameterTypes.map { it.typeName }

        /**
         * The first parameter of [executable] that names a Boolean, bare or wrapped, or `null`.
         *
         * Both spellings, because they are not the same string: a bare Kotlin `Boolean` erases to
         * the JVM primitive and reads `boolean`, while inside a generic it is boxed and reads
         * `java.lang.Boolean`. Checking one alone passes over `List<Boolean>`, which is the shape
         * this predicate exists to catch.
         *
         * **Parameters only**, which is the rule the test below has always stated rather than a
         * narrowing of it: a Boolean this package *computes* is an answer it worked out — `equals`
         * returns one on every class here — and a Boolean it *accepts* is an answer it was handed.
         */
        fun booleanParameterIn(executable: Executable): String? =
            parameterTypeNames(executable).firstOrNull {
                namesType(it, "boolean") || namesType(it, "java.lang.Boolean")
            }

        /** The first parameter of [executable] that names a `String`, bare or wrapped, or `null`. */
        fun stringParameterIn(executable: Executable): String? =
            parameterTypeNames(executable).firstOrNull { namesType(it, STRING_TYPE) }

        /**
         * [executable]'s generic return type when it names a [CheckedEvent], or `null`.
         *
         * A `List<CheckedEvent>` is a door too, and a wider one: whoever holds it holds checked
         * events this library never handed out one at a time, and §4.1's ordering is only as strong
         * as the doors into it.
         */
        fun checkedEventReturnIn(executable: Executable): String? {
            val returned = (executable as? Method)?.genericReturnType?.typeName ?: return null
            return if (namesType(returned, CHECKED_EVENT_TYPE)) returned else null
        }
    }

    @Test
    fun `the sweep finds the classes it is about, by name`() {
        val found = mainClasses().map { it.name.removePrefix("$PACKAGE.") }.toSet()

        for (expected in EXPECTED_BY_NAME) {
            assertTrue(
                expected in found,
                "$expected was not among the main classes of $PACKAGE; found $found",
            )
        }
    }

    @Test
    fun `the checked event has no constructor for a client to reach`() {
        val type = wireType("CheckedEvent")

        assertTrue(type.isInterface, "an interface has no constructor to synthesise for")
        assertEquals(
            0,
            type.constructors.size,
            "a private constructor plus a companion factory emits a *public synthetic* constructor " +
                "with a trailing DefaultConstructorMarker, which a Java client can call with null",
        )
        assertTrue(
            type.declaredConstructors.none { it.isSynthetic },
            "not even a synthetic constructor may exist",
        )
        assertTrue(
            type.isSealed,
            "the JVM PermittedSubclasses attribute is what stops another module implementing this " +
                "interface; it is emitted only from JDK 17 upward, so a toolchain drop would " +
                "silently remove it while every other assertion here stayed green",
        )
    }

    @Test
    fun `every implementation of the checked event is non-public`() {
        val type = wireType("CheckedEvent")
        val implementations = mainClasses().filter { it != type && type.isAssignableFrom(it) }

        assertTrue(
            implementations.isNotEmpty(),
            "the sweep must actually find an implementation; the assertions above are true of any " +
                "interface at all and would pass over a public one",
        )
        for (implementation in implementations) {
            assertFalse(
                Modifier.isPublic(implementation.modifiers),
                "${implementation.name} implements CheckedEvent and is JVM-public, so a client can " +
                    "declare an event id-checked that this library never hashed",
            )
        }
    }

    @Test
    fun `no published constructor or method accepts a Boolean`() {
        // Its own by-name guard rather than only the `inspected` floor below. Every other test here
        // would turn red if `mainClasses()` started resolving to the test output directory; this one
        // would not, because the test tree alone satisfies a bare member count.
        val published = publishedClasses()
        val found = published.map { it.name.removePrefix("$PACKAGE.") }.toSet()
        assertTrue(
            EXPECTED_BY_NAME.all { it in found },
            "the Boolean sweep must be looking at $EXPECTED_BY_NAME, not at whatever classpath entry " +
                "it happened to land on; it found $found",
        )

        var inspected = 0
        for (type in published) {
            for (executable in publishedExecutables(type)) {
                inspected++
                assertNull(
                    booleanParameterIn(executable),
                    "${label(type, executable)} takes ${booleanParameterIn(executable)}. §4.1 " +
                        "requires an implementation compute the id itself; a function that can be " +
                        "told the answer is not a computation, and a relay's say-so is not evidence " +
                        "of anything.",
                )
            }
        }
        assertTrue(inspected > 10, "the sweep inspected only $inspected members, which is not the package")
    }

    /**
     * The control that proves the sweep above is not erasure-blind.
     *
     * Without it, "no published member accepts a Boolean" is satisfied by a predicate that never
     * matches a `List<Boolean>` — which is precisely what the erased-type check it replaced was,
     * because `getParameterTypes()` reports plain `java.util.List` for exactly that parameter. The
     * probe is fed [booleanParameterIn], the predicate the sweep itself runs, and not a copy of it.
     */
    @Test
    fun `the Boolean sweep catches a Boolean hidden inside a generic parameter`() {
        val probe = BooleanParameterProbe::class.java

        for (name in listOf("wrapped", "keyed", "nested", "boxed")) {
            val method = probe.methods.single { it.name == name }
            assertNotNull(
                booleanParameterIn(method),
                "BooleanParameterProbe.$name hides a Boolean the sweep missed — its parameters are " +
                    "${parameterTypeNames(method)}, and an erased-type check sees only List and Map",
            )
        }
        // Caught by the old predicate too: this is what shows the two controls test different things.
        assertNotNull(booleanParameterIn(probe.methods.single { it.name == "direct" }))
        // And not merely "reject every generic": a collection of a permitted type stays permitted.
        assertNull(booleanParameterIn(probe.methods.single { it.name == "permitted" }))
    }

    /** A probe, not a fixture: five parameter lists §4.1 forbids, and one it permits. */
    @Suppress("unused")
    private class BooleanParameterProbe {
        fun wrapped(flags: List<Boolean>): Int = flags.size
        fun keyed(flags: Map<String, Boolean>): Int = flags.size
        fun nested(flags: List<List<Boolean>>): Int = flags.size
        fun boxed(flag: Boolean?): Int = if (flag == true) 1 else 0
        fun direct(flag: Boolean): Int = if (flag) 1 else 0
        fun permitted(names: List<String>): Int = names.size
    }

    @Test
    fun `every published String parameter is on the pinned list`() {
        val found = mutableSetOf<String>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                if (stringParameterIn(executable) != null) {
                    found += label(type, executable)
                }
            }
        }

        assertEquals(
            STRING_PARAMETERS_PERMITTED,
            found,
            "the set of published members taking a String must match the pinned list exactly. A new " +
                "entry may be a status string arriving as evidence that an event is genuine; a " +
                "missing entry means the sweep stopped seeing the package.",
        )
    }

    /**
     * The control that proves the pinned-`String` sweep is not erasure-blind — and that widening it
     * past the erasure did not widen it into a substring match.
     *
     * `List<String>` erases to plain `java.util.List`, so the check this replaced let a member take
     * a whole collection of relay-supplied strings and stay off the pinned list entirely. `builder`
     * is the other half of the control: `java.lang.StringBuilder` *contains* `java.lang.String`, and
     * a member taking one takes no string at all, so a `contains` would add a name the pin never
     * permitted and turn the sweep red for the wrong reason.
     */
    @Test
    fun `the String sweep sees a String inside a generic parameter and not a StringBuilder`() {
        val probe = StringParameterProbe::class.java

        for (name in listOf("wrapped", "keyed", "nested")) {
            val method = probe.methods.single { it.name == name }
            assertNotNull(
                stringParameterIn(method),
                "StringParameterProbe.$name hides a String the sweep missed — its parameters are " +
                    "${parameterTypeNames(method)}, and an erased-type check sees only List and Map",
            )
        }
        assertNotNull(stringParameterIn(probe.methods.single { it.name == "direct" }))
        assertNull(stringParameterIn(probe.methods.single { it.name == "permitted" }))
        assertNull(
            stringParameterIn(probe.methods.single { it.name == "builder" }),
            "java.lang.StringBuilder contains java.lang.String and is not one; a whole-token match " +
                "is what keeps the pinned list from growing an entry nobody wrote",
        )
    }

    /** A probe, not a fixture: four parameter lists that carry a string, and two that do not. */
    @Suppress("unused")
    private class StringParameterProbe {
        fun wrapped(values: List<String>): Int = values.size
        fun keyed(values: Map<String, Int>): Int = values.size
        fun nested(values: List<List<String>>): Int = values.size
        fun direct(value: String): Int = value.length
        fun permitted(values: List<Int>): Int = values.size
        fun builder(value: StringBuilder): Int = value.length
    }

    @Test
    fun `there is exactly one door into a checked event`() {
        val doors = mutableListOf<String>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                if (checkedEventReturnIn(executable) != null) doors += label(type, executable)
            }
        }

        assertEquals(
            listOf("CheckedEvent\$Companion.checkEventId"),
            doors,
            "§4.1's ordering is only as strong as the narrowest door: a second published function " +
                "returning a CheckedEvent is a second way to reach every decoder T9, T10 and T11 " +
                "build on top of it",
        )
    }

    /**
     * The control that proves the door sweep is not erasure-blind.
     *
     * `fun all(): List<CheckedEvent>` reports as plain `java.util.List` to `getReturnType()`, so the
     * erased check this replaced counted it as no door at all while it handed a caller every checked
     * event at once — the widest door in the package, and the one the old sweep could not see.
     */
    @Test
    fun `the door sweep sees a CheckedEvent returned inside a generic type`() {
        val probe = CheckedEventDoorProbe::class.java

        for (name in listOf("wrapped", "keyed", "nested")) {
            val method = probe.methods.single { it.name == name }
            assertNotNull(
                checkedEventReturnIn(method),
                "CheckedEventDoorProbe.$name hands back checked events and the sweep missed it — " +
                    "${method.genericReturnType.typeName} erases past an erased-type check",
            )
        }
        assertNotNull(checkedEventReturnIn(probe.methods.single { it.name == "direct" }))
        assertNull(checkedEventReturnIn(probe.methods.single { it.name == "permitted" }))
    }

    /** A probe, not a fixture: four doors into a checked event, and one shape that is not a door. */
    @Suppress("unused")
    private class CheckedEventDoorProbe {
        fun wrapped(): List<CheckedEvent> = emptyList()
        fun keyed(): Map<String, CheckedEvent> = emptyMap()
        fun nested(): List<List<CheckedEvent>> = emptyList()
        fun direct(): CheckedEvent? = null
        fun permitted(): List<String> = emptyList()
    }

    /**
     * The claim, the event and the bounds, pinned as an exact list rather than scanned.
     *
     * No probe belongs beside this one, and that is a property of the assertion rather than an
     * omission: a whole-list equality cannot be erasure-blind in the dangerous direction, because a
     * `List<String>` in the claim's place erases to `java.util.List` and fails the pin outright.
     * Reading the generic form here buys precision, not reach — `java.util.List<java.lang.String>`
     * is named in the failure message instead of a bare `List`.
     */
    @Test
    fun `the id check takes the claim, the event and the bounds, and nothing that can assert`() {
        val companion = wireType("CheckedEvent\$Companion")
        val check = companion.methods.single { it.name == "checkEventId" }

        assertEquals(
            listOf(
                String::class.java.typeName,
                WireEvent::class.java.typeName,
                WireLimits::class.java.typeName,
            ),
            check.genericParameterTypes.map { it.typeName },
            "the claimed id, the event and §4.3's bounds. Anything else on this parameter list is " +
                "something a relay or a counterparty could say.",
        )
        assertEquals(CheckedEvent::class.java.typeName, check.genericReturnType.typeName)
    }

    /**
     * The trap the payment package fell into and had to be pulled back out of: the sealed
     * interface protects the *checked* type and does nothing for the value types it holds.
     * [EventId] uses the private-constructor-plus-companion-factory idiom, which emits a
     * JVM-public synthetic constructor with a trailing `DefaultConstructorMarker` — so a Java
     * client can write `new EventId(threeBytes, null)` and hold a 3-byte "event id" that §4.3
     * says must have been refused. The invariant therefore lives in `init`, which that
     * constructor also runs, and this test is what proves it does.
     */
    @Test
    fun `the synthetic constructor of EventId still enforces the length`() {
        val type = wireType("EventId")
        val synthetic = type.declaredConstructors.single { it.parameterTypes.size == 2 }
        synthetic.isAccessible = true

        val thrown = assertFailsWith<java.lang.reflect.InvocationTargetException> {
            synthetic.newInstance(ByteArray(3), null)
        }
        val cause = thrown.cause
        assertTrue(cause is WireException, "expected a WireException, got $cause")
        assertEquals(
            WireRejection.WRONG_LENGTH,
            cause.reason,
            "§4.3 requires rejecting a value of the wrong length rather than padding or truncating " +
                "it, on every construction path and not only on the one Kotlin call sites use",
        )
    }

    @Test
    fun `the synthetic constructor of EventId copies the caller's array on the way in`() {
        val type = wireType("EventId")
        val synthetic = type.declaredConstructors.single { it.parameterTypes.size == 2 }
        synthetic.isAccessible = true
        val caller = WireFixtures.sha256("anything".toByteArray())

        val id = synthetic.newInstance(caller, null) as EventId
        val before = id.toHex()
        caller.fill(0)

        assertEquals(
            before,
            id.toHex(),
            "the caller of that constructor keeps its own reference, so an id that did not copy on " +
                "the way in could be rewritten after it was checked",
        )
    }
}
