import java.nio.ByteBuffer
import java.nio.charset.CharacterCodingException
import java.nio.charset.CodingErrorAction
import javax.xml.XMLConstants
import javax.xml.parsers.DocumentBuilderFactory

plugins {
    alias(libs.plugins.kotlin.multiplatform)
}

// ---------------------------------------------------------------------------------
// Vendored test files for common tests. A common test cannot open a file: on the JVM
// the working directory is the module, on Node it is build/js/packages/<name>-test, and
// JavaScript has no class path. So the files common tests read are compiled INTO the
// test code instead: this task writes one Kotlin source, VendoredTestFiles.kt, holding
// each file's exact text as string constants, keyed by its path from the repository
// root. It runs offline and uses nothing but the JDK.
//
// Faithfulness is not assumed: VendoredTestFilesTest (jvmTest) re-reads every listed
// file from disk and asserts the generated text encodes to the same bytes, and that the
// generated key set is exactly the list below.
//
// SHA256LongMsg.rsp (426 KB) is deliberately NOT listed: the NIST vector tests that read
// it stay in jvmTest and open it from disk.
// ---------------------------------------------------------------------------------
abstract class GenerateVendoredTestFiles : DefaultTask() {

    /** Paths from the repository root; they become the lookup keys, in this order. */
    @get:Input
    abstract val paths: ListProperty<String>

    @get:Internal
    abstract val repositoryRoot: DirectoryProperty

    /** The same files, declared as inputs so an edit to any of them regenerates. */
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val sources: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val root = repositoryRoot.get().asFile
        val keys = paths.get()
        require(keys.isNotEmpty()) { "no vendored test files listed" }
        require(keys.toSet().size == keys.size) { "a vendored test file is listed twice: $keys" }
        val out = StringBuilder()
        out.append("// GENERATED by :nenya-core:generateVendoredTestFiles from the files listed in\n")
        out.append("// nenya-core/build.gradle.kts. Do not edit: edit the source file and rebuild.\n")
        out.append("package dev.eryalabs.nenya\n\n")
        out.append("/** The vendored test files, compiled in as text. Keys are paths from the repository root. */\n")
        out.append("internal object VendoredTestFiles {\n\n")
        out.append("    val paths: List<String> = listOf(\n")
        for (key in keys) out.append("        ").append(literal(key)).append(",\n")
        out.append("    )\n\n")
        out.append("    fun text(path: String): String = when (path) {\n")
        keys.forEachIndexed { index, key -> out.append("        ").append(literal(key)).append(" -> file$index\n") }
        out.append("        else -> throw IllegalArgumentException(\"no vendored test file is generated for '\" + path + \"'; generated: \" + paths)\n")
        out.append("    }\n")
        keys.forEachIndexed { index, key ->
            val file = root.resolve(key)
            require(file.isFile) { "vendored test file $key is not at ${file.absolutePath}" }
            val raw = file.readBytes()
            val text = try {
                Charsets.UTF_8.newDecoder()
                    .onMalformedInput(CodingErrorAction.REPORT)
                    .onUnmappableCharacter(CodingErrorAction.REPORT)
                    .decode(ByteBuffer.wrap(raw))
                    .toString()
            } catch (e: CharacterCodingException) {
                throw GradleException("vendored test file $key is not valid UTF-8", e)
            }
            out.append("\n    /** ").append(key.replace("*/", "*\\/")).append(", ").append(raw.size).append(" bytes. */\n")
            out.append("    private val file$index: String by lazy {\n")
            out.append("        buildString(").append(text.length).append(") {\n")
            var start = 0
            while (start < text.length) {
                var end = minOf(start + CHUNK, text.length)
                // Never split a surrogate pair across two literals.
                if (end < text.length && text[end - 1].isHighSurrogate()) end--
                out.append("            append(").append(literal(text.substring(start, end))).append(")\n")
                start = end
            }
            out.append("        }\n")
            out.append("    }\n")
        }
        out.append("}\n")
        val target = outputDirectory.get().asFile.resolve("dev/eryalabs/nenya/VendoredTestFiles.kt")
        target.parentFile.mkdirs()
        target.writeText(out.toString(), Charsets.UTF_8)
    }

    private companion object {
        /** Characters per literal: far below the JVM's 65535-byte constant-pool string limit. */
        const val CHUNK: Int = 8000

        /** A Kotlin string literal: only printable ASCII is written raw, everything else as \uXXXX. */
        fun literal(value: String): String {
            val sb = StringBuilder(value.length + 2).append('"')
            for (c in value) {
                when {
                    c == '\\' || c == '"' || c == '$' -> sb.append('\\').append(c)
                    c.code < 0x20 || c.code > 0x7e -> sb.append("\\u").append(c.code.toString(16).padStart(4, '0'))
                    else -> sb.append(c)
                }
            }
            return sb.append('"').toString()
        }
    }
}

val vendoredTestFilePaths: List<String> = listOf(
    "spec/NENYA-1.md",
    "nenya-core/src/commonTest/resources/spec/nenya-1-11.2-transitions.psv",
    "nenya-core/src/commonTest/resources/vectors/PROVENANCE.md",
    "nenya-core/src/commonTest/resources/vectors/bip340-vectors.csv",
    "nenya-core/src/commonTest/resources/vectors/nip44.vectors.json",
    "nenya-core/src/commonTest/resources/vectors/nist-sha256/SHA256ShortMsg.rsp",
    "nenya-core/src/commonTest/resources/vectors/nist-sha256/SHA256Monte.rsp",
    "nenya-core/src/commonTest/resources/vectors/bolt11/11-payment-encoding.md",
    // §18's gift-wrap row: NIP-59's worked rumor, seal and wrap, and NIP-17's two worked wraps.
    // EventJsonTest parses them out of these two files and recomputes each id, which is the half of
    // the envelope that needs no keys.
    "spec/reference/nip59.md",
    "spec/reference/nip17.md",
)

val generateVendoredTestFiles = tasks.register<GenerateVendoredTestFiles>("generateVendoredTestFiles") {
    description = "Compiles the vendored spec and vector files into a Kotlin source for commonTest."
    paths.set(vendoredTestFilePaths)
    repositoryRoot.set(rootProject.layout.projectDirectory)
    sources.from(vendoredTestFilePaths.map { rootProject.file(it) })
    outputDirectory.set(layout.buildDirectory.dir("generated/vendoredTestFiles/commonTest/kotlin"))
}

kotlin {
    // The published surface is a contract for third-party clients. Explicit API
    // mode forces every public declaration to carry an explicit visibility and
    // return type, so nothing leaks into the ABI by accident. Applies to every target.
    explicitApi()
    jvmToolchain(17)

    // Code that is truly common lives in src/commonMain / src/commonTest and compiles
    // for both targets; everything still JVM-bound lives in src/jvmMain / src/jvmTest.
    jvm()

    // Node only, no browser(): browser tests would need a headless Chrome. Compiling
    // (compileKotlinJs, compileTestKotlinJs) needs no Node, Yarn or npm; running JS tests
    // (jsNodeTest, jsTest, allTests, check, build) and assemble do, and are not loop gates.
    js(IR) {
        moduleName = "nenya"
        nodejs {
            testTask {
                useMocha {
                    // Mocha's default per-test limit is 2000 ms, and it fails a synchronous
                    // test that finishes after that limit even when every assertion passed.
                    // The seeded property tests (BidPropertyTest, ListingPropertyTest,
                    // TagPropertyTest) each build and round-trip a whole generated corpus and
                    // took 2.2-3.0 s on Node 22 on the first JS run, so 7 of them "failed"
                    // on time alone. 30 s is a hang detector, not a performance budget.
                    timeout = "30s"
                }
            }
        }
        binaries.library()
        generateTypeScriptDefinitions()
        useEsModules()
    }

    sourceSets {
        commonTest {
            // The vendored spec and vector files, as Kotlin string constants (see
            // GenerateVendoredTestFiles above). Passing the task provider makes every
            // compilation of commonTest depend on the generator.
            kotlin.srcDir(generateVendoredTestFiles)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        jvmTest.dependencies {
            implementation(libs.junit)
            implementation(libs.kotlin.test.junit)
        }
    }
}

// srcDir(taskProvider) already carries the dependency; stated explicitly for the two
// test compilations the loop gate runs, so a later source-set change cannot drop it.
tasks.named("compileTestKotlinJvm") { dependsOn(generateVendoredTestFiles) }
tasks.named("compileTestKotlinJs") { dependsOn(generateVendoredTestFiles) }

tasks.named<Test>("jvmTest") {
    useJUnit()
    testLogging { events("failed") }
}

// ---------------------------------------------------------------------------------
// Test-count floor. On Gradle 8.13 a Test task that discovers ZERO tests still
// reports BUILD SUCCESSFUL, so a misplaced test tree (or a source-set rename during
// the multiplatform conversion) would pass while running nothing. Every test task
// therefore re-reads its OWN JUnit XML after it runs and fails the build when the
// result directory is empty or fewer tests executed than its floor (root
// gradle.properties). The location comes from the task, never a hardcoded path, so
// the guard survives `test` becoming `jvmTest`. JDK XML parser only.
//
// Two floors, because the two kinds of test task run different suites:
//   - JVM Test tasks (jvmTest) run commonTest AND jvmTest: floor `nenya.minTests`.
//   - Kotlin/JS test tasks (jsNodeTest) run commonTest only, and are NOT Gradle `Test`
//     tasks (KotlinJsTest extends AbstractTestTask), so the JVM floor never reached
//     them: floor `nenya.minJsTests`. Neither runs in the loop gate.
// ---------------------------------------------------------------------------------
val minTestsProperty: Provider<String> = providers.gradleProperty("nenya.minTests")
val minJsTestsProperty: Provider<String> = providers.gradleProperty("nenya.minJsTests")

tasks.withType<AbstractTestTask>().configureEach {
    val taskPath = path
    val isJvm = this is Test
    val propertyName = if (isJvm) "nenya.minTests" else "nenya.minJsTests"
    val floorProperty = if (isJvm) minTestsProperty else minJsTestsProperty
    doLast {
        // Read from the task at execution time: a provider mapped off this output property
        // at configuration time loses its task association and Gradle refuses to query it.
        val xmlDir = (this as AbstractTestTask).reports.junitXml.outputLocation.get().asFile
        val floorText = floorProperty.orNull
            ?: throw GradleException("$taskPath: Gradle property $propertyName is not set (expected in the root gradle.properties)")
        val floor = floorText.trim().toIntOrNull()
            ?: throw GradleException("$taskPath: $propertyName must be an integer, was '$floorText'")
        val dir = xmlDir
        val results = dir.listFiles { f -> f.isFile && f.name.startsWith("TEST-") && f.name.endsWith(".xml") }
            ?.sortedBy { it.name }
            .orEmpty()
        if (results.isEmpty()) {
            throw GradleException(
                "$taskPath: test-count floor FAILED: expected at least $floor executed tests, " +
                    "actual 0 - no JUnit XML result files in ${dir.absolutePath}"
            )
        }
        val factory = DocumentBuilderFactory.newInstance().apply {
            setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true)
            setFeature("http://apache.org/xml/features/disallow-doctype-decl", true)
        }
        var tests = 0
        var skipped = 0
        for (file in results) {
            val suite = factory.newDocumentBuilder().parse(file).documentElement
            fun count(name: String): Int = suite.getAttribute(name).ifEmpty { "0" }.toInt()
            tests += count("tests")
            skipped += count("skipped")
        }
        val executed = tests - skipped
        if (executed < floor) {
            throw GradleException(
                "$taskPath: test-count floor FAILED: expected at least $floor executed tests, " +
                    "actual $executed ($tests reported, $skipped skipped, ${results.size} suites) in ${dir.absolutePath}"
            )
        }
        logger.lifecycle("$taskPath: test-count floor OK: $executed executed tests in ${results.size} suites (floor $floor)")
    }
}
