package dev.eryalabs.nenya.seam

import java.lang.reflect.Constructor
import java.lang.reflect.InvocationTargetException
import java.lang.reflect.Method
import java.lang.reflect.Modifier
import java.lang.reflect.ParameterizedType
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * The structural half of §7.4 and of this round's headline rule, enforced by reflection rather
 * than by review.
 *
 * §7.4 says the order id MUST NOT be derived from the coordinate, either pubkey, the price or the
 * time. That is a rule about an **absence**, and a code review can only assert that today's
 * `mint` has no such parameter. This file asserts it about whatever is in the package tomorrow,
 * which is when somebody adds `mint(randomness, coordinate)` "so the ids are easier to debug".
 *
 * The sweep is [SeamReflection]'s, in the shape the payment package specifies and for the reasons
 * given there: `java.lang.reflect` only, `getResources` plural, the `/classes/kotlin/jvm/main/` URL,
 * classes asserted by name.
 */
class SeamStructureTest {

    private companion object {

        /** The classes this sweep is *about*, by name rather than by count. */
        val EXPECTED_BY_NAME: Set<String> = setOf(
            "Seam",
            "Signer",
            "RelayTransport",
            "Wallet",
            "NenyaClock",
            "Randomness",
            "Secp256k1Ops",
            "SeamAnswer",
            "SeamCapability",
            "SeamRejection",
            "OrderId",
            "WalletPaymentClaim",
            "WalletPaymentState",
            "SignatureVerdict",
            "RelayAcknowledgement",
        )

        /**
         * Every place on the published surface where a `String` may be a parameter, pinned by
         * name. A new one turns this red and forces a human to say why it is not a status string
         * being smuggled in as evidence. Each of these is either an opaque wire string this
         * library does not parse (an invoice, a serialised event, a NIP-44 payload), §4.3 hex, a
         * diagnostic message, or a compiler-generated enum lookup.
         */
        val STRING_PARAMETERS_PERMITTED: Set<String> = setOf(
            "OrderId\$Companion.ofHex",         // §4.3 hex, 64 characters, either case
            "RelayTransport.publish",           // a serialised event; §3 says it is never trusted
            "RelayTransport.request",           // a serialised NIP-01 filter
            "Signer.signEvent",                 // §4.1's canonical serialisation — the exact bytes
            "Signer.nip44Encrypt",              // a counterparty key in hex, and a plaintext
            "Signer.nip44Decrypt",              // a counterparty key in hex, and a NIP-44 payload
            "Wallet.payInvoice",                // a BOLT-11 string, opaque here — no parser exists
            "Wallet.paymentStatus",             // ditto
            "WalletPaymentClaim.<init>",        // the preimage the wallet *claims*, never evidence
            "SeamAnswer\$Unavailable.<init>",   // the human-readable reason, authored in this library
            "SeamException.<init>",             // the human-readable rejection message
            "SeamCapability.valueOf",           // generated by the Kotlin compiler for enums
            "SeamRejection.valueOf",            // ditto
            "WalletPaymentState.valueOf",       // ditto
            "SignatureVerdict.valueOf",         // ditto
            "RelayAcknowledgement.valueOf",     // ditto
        )

        /**
         * Every place on the published surface where a `ByteArray` may be a parameter, pinned by
         * name — the sibling of [STRING_PARAMETERS_PERMITTED], and added because without it the
         * surface's sharpest claim was unpoliced.
         *
         * [Signer]'s KDoc says "no method here takes or returns a secret key: this interface is the
         * boundary secret key material MUST NOT cross (§12 item 11)". Nothing enforced that:
         * adding `Signer.signWithSecretKey(secretKey: ByteArray)` with a fail-closed default passes
         * every other assertion in this file and every sweep in the package. The two entries below
         * are public data — a BIP-340 x-only key, a message, a signature — and a third entry is a
         * human decision, which is the point of pinning the set.
         */
        val BYTE_ARRAY_PARAMETERS_PERMITTED: Set<String> = setOf(
            "Secp256k1Ops.verifySchnorr", // an x-only public key, a message and a signature
            "OrderId.<init>",             // 32 bytes already drawn from the injected source
        )

        /** Constructors and own public methods, minus everything a client cannot name. */
        fun publishedExecutables(type: Class<*>): List<java.lang.reflect.Executable> =
            type.constructors.toList() + SeamReflection.publishedMethods(type)

        /**
         * Every class a member's return type mentions, including the arguments of a generic.
         *
         * `getReturnType()` is the **erasure**, so a `Wallet.mintOrderId(): SeamAnswer<OrderId>`
         * returns `SeamAnswer` and is invisible to a sweep that reads it. Since every seam method
         * returns `SeamAnswer<T>` by design, that one wrapper is precisely the shape that would
         * defeat these checks — so they walk the type arguments too.
         */
        fun returnedTypes(executable: java.lang.reflect.Executable): List<Class<*>> {
            val method = executable as? Method ?: return emptyList()
            val out = mutableListOf<Class<*>>(method.returnType)
            fun walk(type: java.lang.reflect.Type) {
                when (type) {
                    is Class<*> -> out += type
                    is ParameterizedType -> {
                        (type.rawType as? Class<*>)?.let { out += it }
                        type.actualTypeArguments.forEach { walk(it) }
                    }
                    is java.lang.reflect.WildcardType -> {
                        type.upperBounds.forEach { walk(it) }
                        type.lowerBounds.forEach { walk(it) }
                    }
                }
            }
            walk(method.genericReturnType)
            return out
        }

        fun syntheticConstructorOfOrderId(): Constructor<*> =
            SeamReflection.byName("OrderId").declaredConstructors
                .single { it.parameterTypes.size == 2 }
                .also { it.isAccessible = true }
    }

    @Test
    fun `the sweep finds the classes it is about, by name`() {
        val found = SeamReflection.mainClasses().map { it.name.removePrefix("${SeamReflection.PACKAGE}.") }

        for (expected in EXPECTED_BY_NAME) {
            assertTrue(
                expected in found,
                "$expected was not among the main classes of ${SeamReflection.PACKAGE}; found $found",
            )
        }
    }

    @Test
    fun `no published constructor or method in the seam package accepts a Boolean`() {
        // Its own by-name guard rather than only the `inspected` floor below: a bare member count
        // is satisfied by the test tree alone, so this is the assertion that would stay green if
        // `mainClasses()` started resolving to the wrong output directory.
        val published = SeamReflection.publishedClasses()
        val found = published.map { it.name.removePrefix("${SeamReflection.PACKAGE}.") }.toSet()
        assertTrue(
            EXPECTED_BY_NAME.all { it in found },
            "the Boolean sweep must be looking at $EXPECTED_BY_NAME, not at whatever classpath entry " +
                "it happened to land on; it found $found",
        )

        var inspected = 0
        for (type in published) {
            for (executable in publishedExecutables(type)) {
                inspected++
                for (parameter in executable.parameterTypes) {
                    assertFalse(
                        parameter == java.lang.Boolean.TYPE || parameter == java.lang.Boolean::class.java,
                        "${SeamReflection.label(type, executable)} takes a Boolean. §9.1: a wallet's " +
                            "`isPaid` is not evidence, and a seam that can be *told* the answer is a " +
                            "shorter route to the same lie.",
                    )
                }
            }
        }
        assertTrue(inspected > 20, "the sweep inspected only $inspected members, which is not the package")
    }

    @Test
    fun `every published String parameter is on the pinned list`() {
        val found = mutableSetOf<String>()
        for (type in SeamReflection.publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                if (executable.parameterTypes.any { it == String::class.java }) {
                    found += SeamReflection.label(type, executable)
                }
            }
        }

        assertEquals(
            STRING_PARAMETERS_PERMITTED,
            found,
            "the set of published members taking a String must match the pinned list exactly. A new " +
                "entry may be a status string arriving as evidence; a missing entry means the sweep " +
                "stopped seeing the package.",
        )
    }

    /**
     * The secret-key boundary, made structural. §3 and §12 item 11 both say key material must not
     * cross this surface, and [Signer]'s KDoc claims it does not — this is what makes that true of
     * tomorrow's package rather than only today's.
     */
    @Test
    fun `every published ByteArray parameter is on the pinned list`() {
        val found = mutableSetOf<String>()
        for (type in SeamReflection.publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                if (executable.parameterTypes.any { it == ByteArray::class.java }) {
                    found += SeamReflection.label(type, executable)
                }
            }
        }

        assertEquals(
            BYTE_ARRAY_PARAMETERS_PERMITTED,
            found,
            "the set of published members taking a ByteArray must match the pinned list exactly. A " +
                "new entry may be a secret key arriving on the one boundary §3 says it must never " +
                "cross; a missing entry means the sweep stopped seeing the package.",
        )
    }

    /**
     * No implementing class in this package is public — the assertion T3 spells out for `payment`
     * and T4 for `delivery`, run here for the same reason.
     *
     * The fail-closed defaults are reached through each companion's `FAIL_CLOSED`, and that is the
     * only handle a client should have on them. Making `FailClosedClock` public left the suite
     * green, because the only accidental guard was the pinned `String` list — which catches
     * `FailClosedWallet` and `FailClosedSigner`, whose methods take `String`, and misses the clock,
     * the randomness and the secp256k1 seam entirely. Enforced by coincidence is not enforced.
     */
    @Test
    fun `no implementation of a seam in this package is public`() {
        val implementations = SeamReflection.mainClasses()
            .filter { !it.isInterface && Seam::class.java.isAssignableFrom(it) }

        assertTrue(
            implementations.size >= 6,
            "found only ${implementations.map { it.simpleName }} — one fail-closed default per seam " +
                "is the minimum, so this sweep is looking at the wrong place",
        )
        for (implementation in implementations) {
            assertFalse(
                Modifier.isPublic(implementation.modifiers),
                "${implementation.name} is public. A client reaches a fail-closed default through " +
                    "its companion's FAIL_CLOSED and nowhere else; a public implementation is a " +
                    "second name for it that no test and no KDoc governs.",
            )
        }
    }

    /**
     * §7.4's rule as an absence: `mint` takes the randomness source, and no term of the deal.
     *
     * A derived order id is a correlation handle for anyone who later learns the inputs — and the
     * inputs are exactly what an implementer reaches for when a debugging session wants
     * reproducible ids.
     */
    @Test
    fun `the minting function takes the randomness source and no term of the deal`() {
        val companion = SeamReflection.byName("OrderId\$Companion")
        val mint = companion.methods.single { it.name == "mint" && !it.isSynthetic && !it.isBridge }

        assertEquals(
            listOf(Randomness::class.java),
            mint.parameterTypes.toList(),
            "§7.4: the order id MUST NOT be derived from the coordinate, either pubkey, the price, " +
                "or the time. None of them may be a parameter here.",
        )
        assertEquals(OrderId::class.java, mint.returnType)
    }

    @Test
    fun `the only published ways to obtain an order id are minting one and reading one`() {
        val doors = mutableListOf<String>()
        for (type in SeamReflection.publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                // Generic-aware: a `SeamAnswer<OrderId>` is a door too, and the erasure hides it.
                if (OrderId::class.java in returnedTypes(executable)) {
                    doors += SeamReflection.label(type, executable)
                }
            }
        }

        assertEquals(
            listOf("OrderId\$Companion.mint", "OrderId\$Companion.ofHex").sorted(),
            doors.sorted(),
            "a third published function returning an OrderId — including one wrapped in a " +
                "SeamAnswer, which the erasure hides — would be a third place §7.4's derivation " +
                "rule has to be re-argued",
        )
    }

    /**
     * The trap the payment and delivery packages each had to be pulled out of: the factory idiom
     * protects nothing on its own. [OrderId] uses a private constructor plus a companion factory,
     * which emits a **JVM-public synthetic** constructor with a trailing `DefaultConstructorMarker`
     * — so a Java client can write `new OrderId(threeBytes, null)` and hold a 3-byte "order id"
     * that §4.3 and §7.4 both say must have been refused. The invariant therefore lives in `init`,
     * which that constructor also runs, and this is what proves it does.
     */
    @Test
    fun `the synthetic constructor of OrderId still enforces the length`() {
        val synthetic = syntheticConstructorOfOrderId()

        val thrown = assertFailsWith<InvocationTargetException> { synthetic.newInstance(ByteArray(3), null) }

        val cause = thrown.cause
        assertTrue(cause is SeamException, "expected a SeamException, got $cause")
        assertEquals(
            SeamRejection.WRONG_LENGTH,
            cause.reason,
            "§4.3 requires rejecting a value of the wrong length rather than padding or truncating " +
                "it, on every construction path and not only on the one Kotlin call sites use",
        )
    }

    @Test
    fun `the synthetic constructor of OrderId copies the caller's array on the way in`() {
        val synthetic = syntheticConstructorOfOrderId()
        val caller = SeamFixtures.bytes(OrderId.BYTE_LENGTH, stream = 11L)

        val id = synthetic.newInstance(caller, null) as OrderId
        val before = id.toHex()
        caller.fill(0)

        assertEquals(
            before,
            id.toHex(),
            "the caller of that constructor keeps its own reference, so an id that did not copy on " +
                "the way in could be rewritten after it was read",
        )
    }

    /**
     * §3's list of seams is closed, and the JVM attribute is what keeps it closed. Emitted only
     * from JDK 17 upward, so a toolchain drop would silently remove it while every other
     * assertion in this file stayed green.
     */
    @Test
    fun `Seam is JVM-sealed, so the fail-closed sweep can enumerate the whole list`() {
        assertTrue(Seam::class.java.isInterface)
        assertTrue(
            Seam::class.java.isSealed,
            "without PermittedSubclasses a seam could be declared outside this module and the " +
                "fail-closed sweep would not be enumerating §3's table at all",
        )
        assertEquals(
            0,
            Seam::class.java.constructors.size,
            "an interface has no constructor to synthesise an accessor for",
        )
    }

    /**
     * `SeamAnswer` is the shape every seam answers in, so a third case invented later — a
     * `Maybe`, a `Stale` — would be a third thing every caller has to handle and every fail-closed
     * assertion in this suite has to be re-read against.
     */
    @Test
    fun `SeamAnswer has exactly the two cases the fail-closed rule is written against`() {
        val classes = SeamReflection.mainClasses()
        val answer = SeamReflection.byName("SeamAnswer")
        val cases = classes
            .filter { it != answer && answer.isAssignableFrom(it) }
            .map { it.name.removePrefix("${SeamReflection.PACKAGE}.") }
            .sorted()

        assertEquals(listOf("SeamAnswer\$Provided", "SeamAnswer\$Unavailable"), cases)
        assertTrue(answer.isSealed)
    }
}
