package dev.eryalabs.nenya.seam

import java.lang.reflect.Constructor
import java.lang.reflect.InvocationTargetException
import java.lang.reflect.Method
import java.lang.reflect.Modifier
import java.lang.reflect.ParameterizedType
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The structural half of §7.4 and of this round's headline rule, enforced by reflection rather
 * than by review.
 *
 * §7.4 says the order id MUST NOT be derived from the coordinate, either pubkey, the price or the
 * time. That is a rule about an **absence**, and a code review can only assert that today's
 * `mint` has no such parameter. This file asserts it about whatever is in the package tomorrow,
 * which is when somebody adds `mint(randomness, coordinate)` "so the ids are easier to debug".
 *
 * The sweep is [SeamReflection]'s, in the shape the payment package specifies and for the reasons
 * given there: `java.lang.reflect` only, `getResources` plural, the `/classes/kotlin/jvm/main/` URL,
 * classes asserted by name.
 */
class SeamStructureTest {

    private companion object {

        /** The classes this sweep is *about*, by name rather than by count. */
        val EXPECTED_BY_NAME: Set<String> = setOf(
            "Seam",
            "Signer",
            "EphemeralSigners",
            "RelayTransport",
            "Wallet",
            "NenyaClock",
            "Randomness",
            "Secp256k1Ops",
            "SeamAnswer",
            "SeamCapability",
            "SeamRejection",
            "OrderId",
            "WalletPaymentClaim",
            "WalletPaymentState",
            "SignatureVerdict",
            "RelayAcknowledgement",
            // T35's additions: the answer shape a NIP-44 decryption now has, and the per-relay
            // answers §5.5 wants "this relay did not accept the request" surfaced through.
            "Nip44Decryption",
            "RelayCloseReason",
            "SubscriptionEnd",
            "RelayClaim",
            "RelayDelivery",
        )

        /**
         * Every place on the published surface where a `String` may be a parameter, pinned by
         * name. A new one turns this red and forces a human to say why it is not a status string
         * being smuggled in as evidence. Each of these is either an opaque wire string this
         * library does not parse (an invoice, a serialised event, a NIP-44 payload), §4.3 hex, a
         * diagnostic message, or a compiler-generated enum lookup.
         */
        val STRING_PARAMETERS_PERMITTED: Set<String> = setOf(
            "OrderId\$Companion.ofHex",         // §4.3 hex, 64 characters, either case
            "RelayTransport.publish",           // a serialised event; §3 says it is never trusted
            "RelayTransport.request",           // a serialised NIP-01 filter
            "Signer.signEvent",                 // §4.1's canonical serialisation — the exact bytes
            "Signer.nip44Encrypt",              // a counterparty key in hex, and a plaintext
            "Signer.nip44Decrypt",              // a counterparty key in hex, and a NIP-44 payload
            "Wallet.payInvoice",                // the BOLT-11 string verbatim; this seam parses none
            "Wallet.paymentStatus",             // ditto
            "WalletPaymentClaim.<init>",        // the preimage the wallet *claims*, never evidence
            "SeamAnswer\$Unavailable.<init>",   // the human-readable reason, authored in this library
            "SeamException.<init>",             // the human-readable rejection message
            // T35. The decrypted plaintext a signer hands back (redacted by its own `toString`),
            // and the name a transport gives one relay of its fan-out — never parsed, never dialled.
            "Nip44Decryption\$Decrypted.<init>",
            "RelayClaim.<init>",
            // The serialised events a transport reports it delivered: the same opaque strings
            // `RelayTransport.publish` is pinned for, read back rather than sent. `RelayDelivery`'s
            // own KDoc states the rule — everything in `events` is hostile input (§4.3), including
            // events the implementation believes it authored. Pinned by decision N in loop/VISION.md;
            // visible to this sweep only since T36 began reading inside `List<…>`.
            "RelayDelivery.<init>",
            "SeamCapability.valueOf",           // generated by the Kotlin compiler for enums
            "SeamRejection.valueOf",            // ditto
            "WalletPaymentState.valueOf",       // ditto
            "SignatureVerdict.valueOf",         // ditto
            "RelayAcknowledgement.valueOf",     // ditto
            "RelayCloseReason.valueOf",         // ditto
            "SubscriptionEnd.valueOf",          // ditto
        )

        /**
         * Every place on the published surface where a `ByteArray` may be a parameter, pinned by
         * name — the sibling of [STRING_PARAMETERS_PERMITTED], and added because without it the
         * surface's sharpest claim was unpoliced.
         *
         * [Signer]'s KDoc says "no method here takes or returns a secret key: this interface is the
         * boundary secret key material MUST NOT cross (§12 item 11)". Nothing enforced that:
         * adding `Signer.signWithSecretKey(secretKey: ByteArray)` with a fail-closed default passes
         * every other assertion in this file and every sweep in the package. The two entries below
         * are public data — a BIP-340 x-only key, a message, a signature — and a third entry is a
         * human decision, which is the point of pinning the set.
         */
        val BYTE_ARRAY_PARAMETERS_PERMITTED: Set<String> = setOf(
            "Secp256k1Ops.verifySchnorr", // an x-only public key, a message and a signature
            "OrderId.<init>",             // 32 bytes already drawn from the injected source
        )

        /** Constructors and own public methods, minus everything a client cannot name. */
        fun publishedExecutables(type: Class<*>): List<java.lang.reflect.Executable> =
            type.constructors.toList() + SeamReflection.publishedMethods(type)

        /**
         * Every type [executable] **accepts**, printed in its parameterised form.
         *
         * `getParameterTypes()` is the **erasure**, so a published `fun x(flags: List<Boolean>)`
         * reports `List` and satisfies every parameter rule in this file while handing a caller
         * exactly the shape those rules forbid. `getGenericParameterTypes()` prints
         * `java.util.List<java.lang.Boolean>`, which is what the sweeps below match on.
         *
         * Return types are deliberately not folded in here: each rule that uses this one is about
         * what the surface *accepts*, and [returnedTypes] is the sweep for the other direction.
         */
        fun acceptedTypeNames(executable: java.lang.reflect.Executable): List<String> =
            executable.genericParameterTypes.map { it.typeName }

        /**
         * Whether [typeName] names [sought] itself, or names it inside a generic's type arguments.
         *
         * A bare `contains` is wrong: `java.lang.StringBuilder` contains `java.lang.String`, and a
         * sweep that reported it would be one nobody keeps. So the match is on a whole type token —
         * the character either side must not continue an identifier. Plain string operations rather
         * than a pattern: a pattern is a second grammar to get right in a file whose whole subject
         * is checks that quietly match nothing.
         */
        fun namesType(typeName: String, sought: String): Boolean {
            var from = 0
            while (true) {
                val at = typeName.indexOf(sought, from)
                if (at < 0) return false
                val before = if (at == 0) ' ' else typeName[at - 1]
                val afterAt = at + sought.length
                val after = if (afterAt >= typeName.length) ' ' else typeName[afterAt]
                if (!continuesIdentifier(before) && !continuesIdentifier(after)) return true
                from = at + 1
            }
        }

        private fun continuesIdentifier(character: Char): Boolean =
            character.isLetterOrDigit() || character == '.' || character == '$' || character == '_'

        /**
         * The first type [executable] accepts that names a `Boolean`, or `null` if none does.
         *
         * Both spellings, and the pair is the whole point: a bare Kotlin `Boolean` parameter erases
         * to the JVM primitive, whose `typeName` is `boolean`, while the same type inside a generic
         * is boxed and reads `java.lang.Boolean`. Checking one of the two would leave
         * `List<Boolean>` exactly as invisible as the erased check this replaced.
         */
        fun booleanParameterIn(executable: java.lang.reflect.Executable): String? =
            acceptedTypeNames(executable).firstOrNull {
                namesType(it, "boolean") || namesType(it, "java.lang.Boolean")
            }

        /** The first type [executable] accepts that names a `String`, or `null` if none does. */
        fun stringParameterIn(executable: java.lang.reflect.Executable): String? =
            acceptedTypeNames(executable).firstOrNull { namesType(it, "java.lang.String") }

        /**
         * The first type [executable] accepts that names a `ByteArray`, or `null` if none does.
         *
         * `byte[]` and not `ByteArray`, because `typeName` prints the JVM's spelling for an array.
         * It is also why every expected side in this file is built from `::class.java.typeName` and
         * never from `.name`: the latter is `[B`, which matches no parameterised type at all.
         */
        fun byteArrayParameterIn(executable: java.lang.reflect.Executable): String? =
            acceptedTypeNames(executable).firstOrNull { namesType(it, "byte[]") }

        /**
         * Every class a member's return type mentions, including the arguments of a generic.
         *
         * `getReturnType()` is the **erasure**, so a `Wallet.mintOrderId(): SeamAnswer<OrderId>`
         * returns `SeamAnswer` and is invisible to a sweep that reads it. Since every seam method
         * returns `SeamAnswer<T>` by design, that one wrapper is precisely the shape that would
         * defeat these checks — so they walk the type arguments too.
         */
        fun returnedTypes(executable: java.lang.reflect.Executable): List<Class<*>> {
            val method = executable as? Method ?: return emptyList()
            val out = mutableListOf<Class<*>>(method.returnType)
            fun walk(type: java.lang.reflect.Type) {
                when (type) {
                    is Class<*> -> out += type
                    is ParameterizedType -> {
                        (type.rawType as? Class<*>)?.let { out += it }
                        type.actualTypeArguments.forEach { walk(it) }
                    }
                    is java.lang.reflect.WildcardType -> {
                        type.upperBounds.forEach { walk(it) }
                        type.lowerBounds.forEach { walk(it) }
                    }
                }
            }
            walk(method.genericReturnType)
            return out
        }

        fun syntheticConstructorOfOrderId(): Constructor<*> =
            SeamReflection.byName("OrderId").declaredConstructors
                .single { it.parameterTypes.size == 2 }
                .also { it.isAccessible = true }
    }

    @Test
    fun `the sweep finds the classes it is about, by name`() {
        val found = SeamReflection.mainClasses().map { it.name.removePrefix("${SeamReflection.PACKAGE}.") }

        for (expected in EXPECTED_BY_NAME) {
            assertTrue(
                expected in found,
                "$expected was not among the main classes of ${SeamReflection.PACKAGE}; found $found",
            )
        }
    }

    /**
     * §9.1 as an absence, read through the parameterised type rather than the erasure.
     *
     * This sweep used to read `getParameterTypes()`, which reports `List` for a
     * `fun settle(flags: List<Boolean>)` — so the one rule STOP RULE 12 states most plainly was
     * satisfied by wrapping the lie in a collection. [booleanParameterIn] reads the generic form,
     * and the probe below is what proves it.
     */
    @Test
    fun `no published constructor or method in the seam package accepts a Boolean`() {
        // Its own by-name guard rather than only the `inspected` floor below: a bare member count
        // is satisfied by the test tree alone, so this is the assertion that would stay green if
        // `mainClasses()` started resolving to the wrong output directory.
        val published = SeamReflection.publishedClasses()
        val found = published.map { it.name.removePrefix("${SeamReflection.PACKAGE}.") }.toSet()
        assertTrue(
            EXPECTED_BY_NAME.all { it in found },
            "the Boolean sweep must be looking at $EXPECTED_BY_NAME, not at whatever classpath entry " +
                "it happened to land on; it found $found",
        )

        var inspected = 0
        for (type in published) {
            for (executable in publishedExecutables(type)) {
                inspected++
                val offender = booleanParameterIn(executable)
                assertNull(
                    offender,
                    "${SeamReflection.label(type, executable)} takes a Boolean, as `$offender`. " +
                        "§9.1: a wallet's `isPaid` is not evidence, and a seam that can be *told* " +
                        "the answer is a shorter route to the same lie.",
                )
            }
        }
        assertTrue(inspected > 20, "the sweep inspected only $inspected members, which is not the package")
    }

    /**
     * The control that proves the sweep above is not erasure-blind.
     *
     * Without it, "no published member takes a Boolean" is satisfied by a predicate that never
     * matches a `List<Boolean>` — which is precisely what the erased-type check it replaced was.
     * The probe is fed to [booleanParameterIn], the sweep's **own** predicate: a control that
     * exercised a second copy of the check would prove nothing about the first, which is the exact
     * failure mode this conversion exists to fix.
     */
    @Test
    fun `the Boolean sweep catches a Boolean hidden inside a generic parameter`() {
        val probe = BooleanCollectionProbe::class.java
        for (name in listOf("wrapped", "keyed", "nested")) {
            val method = probe.methods.single { it.name == name }
            assertNotNull(
                booleanParameterIn(method),
                "BooleanCollectionProbe.$name hides a Boolean and the sweep's own predicate missed " +
                    "it — ${acceptedTypeNames(method)} erases past a check that reads the erasure",
            )
        }
        // Caught by the old predicate too: this is what shows the two controls test different things.
        assertNotNull(booleanParameterIn(probe.methods.single { it.name == "direct" }))
        // Not merely "reject every generic".
        assertNull(booleanParameterIn(probe.methods.single { it.name == "permitted" }))
    }

    /**
     * A probe, not a fixture: three shapes that hide the forbidden type, the plain one the erased
     * check already caught, and a generic of a permitted type that must stay uncaught.
     *
     * Declared here and never in `src/jvmMain`, and its members are found by reflection, so a probe
     * that failed to compile into the test output cannot pass vacuously — `single` throws.
     */
    @Suppress("unused")
    private class BooleanCollectionProbe {
        fun wrapped(flags: List<Boolean>): Int = flags.size
        fun keyed(flags: Map<String, Boolean>): Int = flags.size
        fun nested(flags: List<List<Boolean>>): Int = flags.size
        fun direct(flag: Boolean): Int = if (flag) 1 else 0
        fun permitted(names: List<String>): Int = names.size
    }

    /**
     * The pinned list, read through the parameterised type: a `List<String>` is a String parameter.
     *
     * The erased form of this sweep asked only whether a parameter *was* `String`, so a member
     * taking `List<String>` or `Map<String, String>` joined the published surface without a human
     * ever being asked why it is not a status string smuggled in as evidence — which is the entire
     * job of the pin.
     */
    @Test
    fun `every published String parameter is on the pinned list`() {
        val found = mutableSetOf<String>()
        for (type in SeamReflection.publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                if (stringParameterIn(executable) != null) {
                    found += SeamReflection.label(type, executable)
                }
            }
        }

        assertEquals(
            STRING_PARAMETERS_PERMITTED,
            found,
            "the set of published members taking a String must match the pinned list exactly. A new " +
                "entry may be a status string arriving as evidence; a missing entry means the sweep " +
                "stopped seeing the package.",
        )
    }

    /**
     * The control that proves the pin above is not erasure-blind.
     *
     * Fed to [stringParameterIn], the sweep's own predicate. A member taking `List<String>` is a
     * member taking strings, and before the conversion it could join the surface without appearing
     * in [STRING_PARAMETERS_PERMITTED] at all.
     */
    @Test
    fun `the String pin catches a String hidden inside a generic parameter`() {
        val probe = StringCollectionProbe::class.java
        for (name in listOf("wrapped", "keyed", "nested")) {
            val method = probe.methods.single { it.name == name }
            assertNotNull(
                stringParameterIn(method),
                "StringCollectionProbe.$name hides a String and the pin's own predicate missed it — " +
                    "${acceptedTypeNames(method)} erases past a check that reads the erasure",
            )
        }
        // Caught by the old predicate too: this is what shows the two controls test different things.
        assertNotNull(stringParameterIn(probe.methods.single { it.name == "direct" }))
        // Not merely "reject every generic", and not fooled by a name a String's name is inside of.
        assertNull(stringParameterIn(probe.methods.single { it.name == "permitted" }))
        assertNull(stringParameterIn(probe.methods.single { it.name == "neighbour" }))
    }

    /**
     * A probe, not a fixture. `neighbour` is the one that earns [namesType]: `java.lang.StringBuilder`
     * contains `java.lang.String`, and a sweep built on `contains` would report it.
     */
    @Suppress("unused")
    private class StringCollectionProbe {
        fun wrapped(events: List<String>): Int = events.size
        fun keyed(events: Map<String, Int>): Int = events.size
        fun nested(events: List<List<String>>): Int = events.size
        fun direct(event: String): Int = event.length
        fun permitted(counts: List<Int>): Int = counts.size
        fun neighbour(builder: StringBuilder): Int = builder.length
    }

    /**
     * The secret-key boundary, made structural. §3 and §12 item 11 both say key material must not
     * cross this surface, and [Signer]'s KDoc claims it does not — this is what makes that true of
     * tomorrow's package rather than only today's.
     *
     * Read through the parameterised type, because the erased form of this sweep would have let
     * `Signer.signWithSecretKeys(keys: List<ByteArray>)` cross that boundary unpinned.
     */
    @Test
    fun `every published ByteArray parameter is on the pinned list`() {
        val found = mutableSetOf<String>()
        for (type in SeamReflection.publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                if (byteArrayParameterIn(executable) != null) {
                    found += SeamReflection.label(type, executable)
                }
            }
        }

        assertEquals(
            BYTE_ARRAY_PARAMETERS_PERMITTED,
            found,
            "the set of published members taking a ByteArray must match the pinned list exactly. A " +
                "new entry may be a secret key arriving on the one boundary §3 says it must never " +
                "cross; a missing entry means the sweep stopped seeing the package.",
        )
    }

    /**
     * The control that proves the pin above is not erasure-blind.
     *
     * Fed to [byteArrayParameterIn], the sweep's own predicate. A secret key hidden one collection
     * deep is still a secret key crossing the boundary §12 item 11 closes, and it is the shape an
     * implementer reaches for the day a signer wants to sign in a batch.
     */
    @Test
    fun `the ByteArray pin catches a ByteArray hidden inside a generic parameter`() {
        val probe = ByteArrayCollectionProbe::class.java
        for (name in listOf("wrapped", "keyed", "nested")) {
            val method = probe.methods.single { it.name == name }
            assertNotNull(
                byteArrayParameterIn(method),
                "ByteArrayCollectionProbe.$name hides a ByteArray and the pin's own predicate " +
                    "missed it — ${acceptedTypeNames(method)} erases past a check that reads the " +
                    "erasure",
            )
        }
        // Caught by the old predicate too: this is what shows the two controls test different things.
        assertNotNull(byteArrayParameterIn(probe.methods.single { it.name == "direct" }))
        // Not merely "reject every generic".
        assertNull(byteArrayParameterIn(probe.methods.single { it.name == "permitted" }))
    }

    /** A probe, not a fixture: `byte[]` is the spelling `typeName` prints, and the one matched. */
    @Suppress("unused")
    private class ByteArrayCollectionProbe {
        fun wrapped(keys: List<ByteArray>): Int = keys.size
        fun keyed(keys: Map<String, ByteArray>): Int = keys.size
        fun nested(keys: List<List<ByteArray>>): Int = keys.size
        fun direct(key: ByteArray): Int = key.size
        fun permitted(names: List<String>): Int = names.size
    }

    /**
     * No implementing class in this package is public — the assertion T3 spells out for `payment`
     * and T4 for `delivery`, run here for the same reason.
     *
     * The fail-closed defaults are reached through each companion's `FAIL_CLOSED`, and that is the
     * only handle a client should have on them. Making `FailClosedClock` public left the suite
     * green, because the only accidental guard was the pinned `String` list — which catches
     * `FailClosedWallet` and `FailClosedSigner`, whose methods take `String`, and misses the clock,
     * the randomness and the secp256k1 seam entirely. Enforced by coincidence is not enforced.
     */
    @Test
    fun `no implementation of a seam in this package is public`() {
        val implementations = SeamReflection.mainClasses()
            .filter { !it.isInterface && Seam::class.java.isAssignableFrom(it) }

        assertTrue(
            implementations.size >= 7,
            "found only ${implementations.map { it.simpleName }} — one fail-closed default per seam " +
                "is the minimum, so this sweep is looking at the wrong place",
        )
        for (implementation in implementations) {
            assertFalse(
                Modifier.isPublic(implementation.modifiers),
                "${implementation.name} is public. A client reaches a fail-closed default through " +
                    "its companion's FAIL_CLOSED and nowhere else; a public implementation is a " +
                    "second name for it that no test and no KDoc governs.",
            )
        }
    }

    /**
     * §7.4's rule as an absence: `mint` takes the randomness source, and no term of the deal.
     *
     * A derived order id is a correlation handle for anyone who later learns the inputs — and the
     * inputs are exactly what an implementer reaches for when a debugging session wants
     * reproducible ids.
     *
     * Pinned on the parameterised type names, and pinned rather than scanned, so this one needs no
     * probe of its own: an exact whole-list equality cannot be erasure-blind in the dangerous
     * direction, because `mint(seed: List<PaymentHash>)` erases to `List` and fails the pin
     * outright. The expected side is built from `typeName` and never from `name`, which for an
     * array would be `[B` and would red-line a parameter the JDK prints as `byte[]`.
     */
    @Test
    fun `the minting function takes the randomness source and no term of the deal`() {
        val companion = SeamReflection.byName("OrderId\$Companion")
        val mint = companion.methods.single { it.name == "mint" && !it.isSynthetic && !it.isBridge }

        assertEquals(
            listOf(Randomness::class.java.typeName),
            mint.genericParameterTypes.map { it.typeName },
            "§7.4: the order id MUST NOT be derived from the coordinate, either pubkey, the price, " +
                "or the time. None of them may be a parameter here.",
        )
        assertEquals(OrderId::class.java.typeName, mint.genericReturnType.typeName)
    }

    @Test
    fun `the only published ways to obtain an order id are minting one and reading one`() {
        val doors = mutableListOf<String>()
        for (type in SeamReflection.publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                // Generic-aware: a `SeamAnswer<OrderId>` is a door too, and the erasure hides it.
                if (OrderId::class.java in returnedTypes(executable)) {
                    doors += SeamReflection.label(type, executable)
                }
            }
        }

        assertEquals(
            listOf("OrderId\$Companion.mint", "OrderId\$Companion.ofHex").sorted(),
            doors.sorted(),
            "a third published function returning an OrderId — including one wrapped in a " +
                "SeamAnswer, which the erasure hides — would be a third place §7.4's derivation " +
                "rule has to be re-argued",
        )
    }

    /**
     * The trap the payment and delivery packages each had to be pulled out of: the factory idiom
     * protects nothing on its own. [OrderId] uses a private constructor plus a companion factory,
     * which emits a **JVM-public synthetic** constructor with a trailing `DefaultConstructorMarker`
     * — so a Java client can write `new OrderId(threeBytes, null)` and hold a 3-byte "order id"
     * that §4.3 and §7.4 both say must have been refused. The invariant therefore lives in `init`,
     * which that constructor also runs, and this is what proves it does.
     */
    @Test
    fun `the synthetic constructor of OrderId still enforces the length`() {
        val synthetic = syntheticConstructorOfOrderId()

        val thrown = assertFailsWith<InvocationTargetException> { synthetic.newInstance(ByteArray(3), null) }

        val cause = thrown.cause
        assertTrue(cause is SeamException, "expected a SeamException, got $cause")
        assertEquals(
            SeamRejection.WRONG_LENGTH,
            cause.reason,
            "§4.3 requires rejecting a value of the wrong length rather than padding or truncating " +
                "it, on every construction path and not only on the one Kotlin call sites use",
        )
    }

    @Test
    fun `the synthetic constructor of OrderId copies the caller's array on the way in`() {
        val synthetic = syntheticConstructorOfOrderId()
        val caller = SeamFixtures.bytes(OrderId.BYTE_LENGTH, stream = 11L)

        val id = synthetic.newInstance(caller, null) as OrderId
        val before = id.toHex()
        caller.fill(0)

        assertEquals(
            before,
            id.toHex(),
            "the caller of that constructor keeps its own reference, so an id that did not copy on " +
                "the way in could be rewritten after it was read",
        )
    }

    /**
     * §3's list of seams is closed, and the JVM attribute is what keeps it closed. Emitted only
     * from JDK 17 upward, so a toolchain drop would silently remove it while every other
     * assertion in this file stayed green.
     */
    @Test
    fun `Seam is JVM-sealed, so the fail-closed sweep can enumerate the whole list`() {
        assertTrue(Seam::class.java.isInterface)
        assertTrue(
            Seam::class.java.isSealed,
            "without PermittedSubclasses a seam could be declared outside this module and the " +
                "fail-closed sweep would not be enumerating §3's table at all",
        )
        assertEquals(
            0,
            Seam::class.java.constructors.size,
            "an interface has no constructor to synthesise an accessor for",
        )
    }

    /**
     * `SeamAnswer` is the shape every seam answers in, so a third case invented later — a
     * `Maybe`, a `Stale` — would be a third thing every caller has to handle and every fail-closed
     * assertion in this suite has to be re-read against.
     */
    @Test
    fun `SeamAnswer has exactly the two cases the fail-closed rule is written against`() {
        val classes = SeamReflection.mainClasses()
        val answer = SeamReflection.byName("SeamAnswer")
        val cases = classes
            .filter { it != answer && answer.isAssignableFrom(it) }
            .map { it.name.removePrefix("${SeamReflection.PACKAGE}.") }
            .sorted()

        assertEquals(listOf("SeamAnswer\$Provided", "SeamAnswer\$Unavailable"), cases)
        assertTrue(answer.isSealed)
    }
}
