package dev.eryalabs.nenya.delivery

import dev.eryalabs.nenya.JdkRandom
import dev.eryalabs.nenya.oracleSha256

/**
 * The generator behind every blob fixture in this package.
 *
 * This is not a scratch file: the queue's Definition of done forbids a hash or any other
 * encoded value appearing in a test as something somebody typed out. Every fixture here is
 * therefore *computed* — the blob bytes by `java.util.Random`'s algorithm ([JdkRandom]) pinned to
 * [SEED], and every `x` and `ox` by the platform's SHA-256 ([oracleSha256], `MessageDigest` on
 * the JVM). A reviewer can change [SEED], re-run the
 * suite, and every property must still hold.
 *
 * The one fixture that is **not** generated here is the externally-authored anchor: the
 * SHA-256 of the vendored `vectors/nip44.vectors.json`, which §18 of `spec/NENYA-1.md`
 * publishes and which `DeliveryVerificationTest` parses out of the specification at test time
 * rather than transcribing. See `SpecAnchor`.
 *
 * ### What a "blob" is here, and what it deliberately is not
 *
 * A [Blob] carries two byte arrays, `served` and `plaintext`, and a commitment whose `x` and
 * `ox` are their digests. The two arrays are **unrelated random bytes**, not a real
 * AES-256-GCM ciphertext and its plaintext, because this library does not encrypt or decrypt
 * (§10.4 step 2 is the caller's — see [DeliveryCheck.GCM_AUTHENTICATION]). Nothing under test
 * relates the two arrays either: §10.4 steps 1 and 3 are two independent SHA-256 comparisons
 * whose *order* is the thing being enforced. Generating a real ciphertext would add a
 * dependency-free but entirely unexercised code path to a test file, and would tempt a later
 * reader into thinking the library decrypts.
 *
 * The two arrays are always different lengths from each other by construction, so a verifier
 * that swapped `x` for `ox` cannot pass by accident on a length coincidence.
 */
internal object DeliveryFixtures {

    /**
     * Pinned so a failure is reproducible. `java.util.Random`'s algorithm rather than
     * `kotlin.random` is deliberate: it is specified by the JDK, so this file produces the same runs
     * on any JVM a reviewer re-runs it on — and, as [JdkRandom], the same runs on JavaScript.
     */
    const val SEED: Long = 20260910L

    /** The MIME type every generated commitment carries, in §10.1's own example's value. */
    const val MIME_TYPE: String = "video/mp4"

    /**
     * A generated deliverable: the served (encrypted) bytes, the plaintext bytes, and the
     * §10.1 commitment whose `x` and `ox` are their computed digests.
     */
    data class Blob(
        val served: ByteArray,
        val plaintext: ByteArray,
        val commitment: DeliverableCommitment,
    ) {

        /** The §10.3 release that matches this commitment on all four operands. */
        fun matchingRelease(): DeliverableRelease = DeliverableRelease(
            x = commitment.x,
            ox = commitment.ox,
            fileType = commitment.mimeType,
            sizeBytes = commitment.sizeBytes,
        )

        /**
         * Generated by the `data class` and unused; overridden only because Kotlin warns that
         * the generated one compares arrays by identity. Identity is in fact what a fixture
         * wants, so this is the generated behaviour written down rather than a change to it.
         * `super.hashCode()` is `Any`'s identity hash — `System.identityHashCode` on the JVM.
         */
        override fun equals(other: Any?): Boolean = this === other

        override fun hashCode(): Int = super.hashCode()
    }

    /**
     * [count] blobs, **provably distinct**, which is load-bearing rather than incidental: a
     * cross-rejection property over blobs that were not distinct would be asserting that a blob
     * differs from itself, and would fail for a reason that has nothing to do with the verifier.
     *
     * Random bytes alone do not give that guarantee at this sample size. A run of 10 000 blobs
     * drawn at lengths cycling from 1 upward puts 157 of them at one byte, where there are only
     * 256 possible values — the birthday collision is not a tail risk, it is a certainty. So
     * the first [INDEX_PREFIX] bytes of every array are that blob's index, big-endian, and the
     * rest are random: distinctness by construction, entropy for everything else.
     *
     * The plaintext is always longer than its own served bytes, so a verifier that swapped `x`
     * for `ox` cannot slip past on a length coincidence.
     */
    fun blobs(count: Int): List<Blob> {
        val random = JdkRandom(SEED)
        return List(count) { index ->
            val servedLength = INDEX_PREFIX + 1 + (index % 57)
            val plaintextLength = servedLength + 1 + (index % 17)
            val served = generate(random, servedLength, index)
            val plaintext = generate(random, plaintextLength, index)
            Blob(served, plaintext, commitmentFor(served, plaintext))
        }
    }

    /** Bytes of [index] written big-endian at the head of every generated array. */
    private const val INDEX_PREFIX: Int = 4

    private fun generate(random: JdkRandom, length: Int, index: Int): ByteArray {
        val bytes = ByteArray(length)
        random.nextBytes(bytes)
        for (byte in 0 until INDEX_PREFIX) {
            bytes[byte] = (index ushr (8 * (INDEX_PREFIX - 1 - byte))).toByte()
        }
        return bytes
    }

    /** One blob, drawn from the same seeded run so a single-case test and a property agree. */
    fun blob(): Blob = blobs(1).single()

    /**
     * The §10.1 commitment a provider would publish for these bytes: `x` is the SHA-256 of the
     * served bytes, `ox` the SHA-256 of the plaintext, `size` the served length. All computed,
     * none typed.
     */
    fun commitmentFor(served: ByteArray, plaintext: ByteArray): DeliverableCommitment =
        DeliverableCommitment(
            x = hashOf(served),
            ox = hashOf(plaintext),
            mimeType = MIME_TYPE,
            sizeBytes = served.size.toLong(),
        )

    /** `SHA-256(bytes)` as a [DeliverableHash], built through the public hex reader. */
    fun hashOf(bytes: ByteArray): DeliverableHash = DeliverableHash.ofHex(lowerHex(sha256(bytes)))

    fun sha256(bytes: ByteArray): ByteArray = oracleSha256(bytes)

    /** §4.3's canonical form: lowercase, unpadded. */
    fun lowerHex(bytes: ByteArray): String {
        val digits = "0123456789abcdef"
        val out = StringBuilder(bytes.size * 2)
        for (byte in bytes) {
            val value = byte.toInt() and 0xff
            out.append(digits[value ushr 4]).append(digits[value and 0x0f])
        }
        return out.toString()
    }
}
