package dev.eryalabs.nenya.delivery

import java.io.File
import java.lang.reflect.Executable
import java.lang.reflect.Modifier
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * The structural half of §10.4's ordering and of STOP RULE 12, enforced by reflection rather
 * than by review.
 *
 * §11.3 invariant 4 says `settled` is reachable only after the buyer's own hash computation.
 * A code review can only assert that today's code obeys that; this file asserts it about
 * whatever is in the package tomorrow, which is when somebody adds
 * `verifyPlaintextBytes(..., providerSaysDelivered: Boolean)` in a hurry, or a second factory
 * that hands out a [DeliveryEvidence] without a [ServedBytesVerified] in front of it.
 *
 * The sweep is the one the payment package's `PaymentStructureTest` specifies, over
 * `dev/eryalabs/nenya/delivery`, and every note there applies here:
 *
 * - **`java.lang.reflect` only.** `kotlin-reflect` is not on any classpath and STOP RULE 11
 *   forbids adding one. `KClass.members` and `KClass.constructors` compile and then throw
 *   `KotlinReflectionNotSupportedError`; `kotlin.reflect.full.*` does not compile at all.
 * - **`getResources`, plural.** The singular form resolves to the **test** output directory,
 *   because `build/classes/kotlin/test` precedes `build/classes/kotlin/main` on the test
 *   runtime classpath and this repo mirrors package names into its test tree. A sweep built on
 *   it would enumerate this very file's class, never see [DeliveryEvidence], and pass with the
 *   implementation entirely absent.
 * - **Classes asserted by name.** A count is satisfied by whatever the wrong classpath entry
 *   happened to contain, which is exactly the failure the plural form exists to avoid.
 */
class DeliveryStructureTest {

    private companion object {

        const val PACKAGE: String = "dev.eryalabs.nenya.delivery"

        /** The classes this sweep is *about*, by name rather than by count. */
        val EXPECTED_BY_NAME: Set<String> = setOf(
            "DeliverableCommitment",
            "DeliverableRelease",
            "DeliverableHash",
            "ServedBytesVerified",
            "DeliveryEvidence",
            "DeliveryCheck",
        )

        /**
         * Every place on the published surface where a `String` may be a parameter, pinned by
         * name. A new one turns this red and forces a human to say why it is not a status
         * string being smuggled in as evidence of delivery. Each of these is either a hex
         * reader (§4.3's encoding, not a status), a MIME type §10.3 compares byte-identically,
         * a diagnostic message, or a compiler-generated enum lookup.
         */
        val STRING_PARAMETERS_PERMITTED: Set<String> = setOf(
            "DeliverableHash\$Companion.ofHex",  // §4.3 hex, 64 characters, either case
            "DeliverableCommitment.<init>",      // §10.1's ["m", ...] value
            "DeliverableRelease.<init>",         // §10.3's ["file-type", ...] value, nullable
            "DeliveryException.<init>",          // the human-readable rejection message
            "DeliveryCheck.valueOf",             // generated by the Kotlin compiler for enums
            "DeliveryRejection.valueOf",         // ditto
        )

        fun mainClasses(): List<Class<*>> {
            val loader = DeliveryStructureTest::class.java.classLoader
            val urls = loader.getResources(PACKAGE.replace('.', '/')).toList()
            val main = urls.firstOrNull { it.path.contains("/classes/kotlin/main/") }
                ?: fail(
                    "no /classes/kotlin/main/ URL for $PACKAGE among $urls — the sweep would " +
                        "otherwise enumerate the test output directory and pass with no implementation",
                )
            val directory = File(main.toURI())
            val files = directory.listFiles { file: File -> file.name.endsWith(".class") }
                ?: fail("${directory.absolutePath} is not a readable directory")
            assertTrue(files.isNotEmpty(), "${directory.absolutePath} holds no classes")
            // The class files this package compiled to at commit 6432814, pinned as a floor so a
            // partial output directory after a source-layout move goes red instead of sweeping less.
            val pinned = 14
            assertTrue(
                files.size >= pinned,
                "${directory.absolutePath} holds ${files.size} class file(s); at least $pinned were pinned",
            )
            return files.map { Class.forName("$PACKAGE.${it.name.removeSuffix(".class")}", false, loader) }
        }

        fun publishedClasses(): List<Class<*>> =
            mainClasses().filter { Modifier.isPublic(it.modifiers) && !it.isSynthetic }

        /** Constructors and own public methods, minus everything a client cannot name. */
        fun publishedExecutables(type: Class<*>): List<Executable> =
            type.constructors.toList() +
                type.methods.filter {
                    it.declaringClass == type && !it.isSynthetic && !it.isBridge && '$' !in it.name
                }

        fun label(type: Class<*>, executable: Executable): String {
            val simple = type.name.removePrefix("$PACKAGE.")
            val member = if (executable is java.lang.reflect.Constructor<*>) "<init>" else executable.name
            return "$simple.$member"
        }

        fun evidenceType(name: String): Class<*> = mainClasses().single { it.name == "$PACKAGE.$name" }
    }

    @Test
    fun `the sweep finds the classes it is about, by name`() {
        val found = mainClasses().map { it.name.removePrefix("$PACKAGE.") }.toSet()

        for (expected in EXPECTED_BY_NAME) {
            assertTrue(
                expected in found,
                "$expected was not among the main classes of $PACKAGE; found $found",
            )
        }
    }

    @Test
    fun `neither evidence type has a constructor for a client to reach`() {
        for (name in listOf("ServedBytesVerified", "DeliveryEvidence")) {
            val type = evidenceType(name)

            assertTrue(type.isInterface, "$name: an interface has no constructor to synthesise for")
            assertEquals(
                0,
                type.constructors.size,
                "$name: a private constructor plus a companion factory emits a *public synthetic* " +
                    "constructor with a trailing DefaultConstructorMarker, which a Java client can " +
                    "call with null",
            )
            assertTrue(
                type.declaredConstructors.none { it.isSynthetic },
                "$name: not even a synthetic constructor may exist",
            )
            assertTrue(
                type.isSealed,
                "$name: the JVM PermittedSubclasses attribute is what stops another module " +
                    "implementing this interface; it is emitted only from JDK 17 upward, so a " +
                    "toolchain drop would silently remove it while every other assertion stayed green",
            )
        }
    }

    @Test
    fun `every implementation of either evidence type is non-public`() {
        val classes = mainClasses()

        for (name in listOf("ServedBytesVerified", "DeliveryEvidence")) {
            val type = evidenceType(name)
            val implementations = classes.filter { it != type && type.isAssignableFrom(it) }

            assertTrue(
                implementations.isNotEmpty(),
                "$name: the sweep must actually find an implementation; the assertions above are " +
                    "true of any interface at all and would pass over a public one",
            )
            for (implementation in implementations) {
                assertFalse(
                    Modifier.isPublic(implementation.modifiers),
                    "${implementation.name} implements $name and is JVM-public, so a client can " +
                        "construct evidence of a delivery that never happened",
                )
            }
        }
    }

    @Test
    fun `no published constructor or method accepts a Boolean`() {
        // Its own by-name guard rather than only the `inspected` floor below. Every other test
        // here would turn red if `mainClasses()` started resolving to the test output directory;
        // this one would not, because the test tree alone satisfies a bare member count.
        val published = publishedClasses()
        val found = published.map { it.name.removePrefix("$PACKAGE.") }.toSet()
        assertTrue(
            EXPECTED_BY_NAME.all { it in found },
            "the Boolean sweep must be looking at $EXPECTED_BY_NAME, not at whatever classpath " +
                "entry it happened to land on; it found $found",
        )

        var inspected = 0
        for (type in published) {
            for (executable in publishedExecutables(type)) {
                inspected++
                for (parameter in executable.parameterTypes) {
                    assertFalse(
                        parameter == java.lang.Boolean.TYPE || parameter == java.lang.Boolean::class.java,
                        "${label(type, executable)} takes a Boolean. §11.3 invariant 4: `settled` is " +
                            "reachable only after the buyer's own hash computation, and a function " +
                            "that can be told the answer is not a computation",
                    )
                }
            }
        }
        assertTrue(inspected > 10, "the sweep inspected only $inspected members, which is not the package")
    }

    @Test
    fun `every published String parameter is on the pinned list`() {
        val found = mutableSetOf<String>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                if (executable.parameterTypes.any { it == String::class.java }) {
                    found += label(type, executable)
                }
            }
        }

        assertEquals(
            STRING_PARAMETERS_PERMITTED,
            found,
            "the set of published members taking a String must match the pinned list exactly. A new " +
                "entry may be a status string arriving as evidence of delivery; a missing entry means " +
                "the sweep stopped seeing the package.",
        )
    }

    @Test
    fun `the served-bytes verifier takes a commitment, bytes and a bound, and nothing that can assert`() {
        val companion = evidenceType("ServedBytesVerified\$Companion")
        val verify = companion.methods.single { it.name == "verifyServedBytes" }

        assertEquals(
            listOf(DeliverableCommitment::class.java, ByteArray::class.java, java.lang.Long.TYPE),
            verify.parameterTypes.toList(),
            "§10.4 step 1 takes the commitment, the bytes and §4.3's bound; anything else on this " +
                "parameter list is something a counterparty could say",
        )
        assertEquals(ServedBytesVerified::class.java, verify.returnType)
    }

    @Test
    fun `the plaintext verifier can only be reached with a verified served-bytes value`() {
        val companion = evidenceType("DeliveryEvidence\$Companion")
        val verify = companion.methods.single { it.name == "verifyPlaintextBytes" }

        assertEquals(
            listOf(ServedBytesVerified::class.java, ByteArray::class.java),
            verify.parameterTypes.toList(),
            "§10.4's ordering is enforced by the type system: there is no way to reach the ox check " +
                "without having passed the x check, and this parameter list is that enforcement",
        )
        assertEquals(DeliveryEvidence::class.java, verify.returnType)
    }

    /**
     * The trap the payment package fell into and had to be pulled back out of: the sealed
     * interface protects the *evidence* type, and does nothing at all for the value types it
     * holds. [DeliverableHash] uses the private-constructor-plus-companion-factory idiom, which
     * emits a JVM-public synthetic constructor with a trailing `DefaultConstructorMarker` — so
     * a Java client can write `new DeliverableHash(threeBytes, null)` and hold a 3-byte "SHA-256
     * commitment" that §4.3 says must have been refused. The invariant therefore lives in
     * `init`, which that constructor also runs, and this test is what proves it does.
     */
    @Test
    fun `the synthetic constructor of DeliverableHash still enforces the length`() {
        val type = evidenceType("DeliverableHash")
        val synthetic = type.declaredConstructors.single { it.parameterTypes.size == 2 }
        synthetic.isAccessible = true

        val thrown = assertFailsWith<java.lang.reflect.InvocationTargetException> {
            synthetic.newInstance(ByteArray(3), null)
        }
        val cause = thrown.cause
        assertTrue(cause is DeliveryException, "expected a DeliveryException, got $cause")
        assertEquals(
            DeliveryRejection.WRONG_LENGTH,
            cause.reason,
            "§4.3 requires rejecting a value of the wrong length rather than padding or truncating " +
                "it, on every construction path and not only on the one Kotlin call sites use",
        )
    }

    @Test
    fun `the synthetic constructor of DeliverableHash copies the caller's array on the way in`() {
        val type = evidenceType("DeliverableHash")
        val synthetic = type.declaredConstructors.single { it.parameterTypes.size == 2 }
        synthetic.isAccessible = true
        val caller = DeliveryFixtures.sha256(byteArrayOf(1, 2, 3))

        val hash = synthetic.newInstance(caller, null) as DeliverableHash
        val before = hash.toHex()
        caller.fill(0)

        assertEquals(
            before,
            hash.toHex(),
            "the caller of that constructor keeps its own reference, so a commitment that did not " +
                "copy on the way in could be rewritten after it was read",
        )
    }

    @Test
    fun `there is exactly one door into each evidence type`() {
        val doors = mutableMapOf<String, MutableList<String>>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                val returned = (executable as? java.lang.reflect.Method)?.returnType ?: continue
                val name = returned.name.removePrefix("$PACKAGE.")
                if (name == "ServedBytesVerified" || name == "DeliveryEvidence") {
                    doors.getOrPut(name) { mutableListOf() } += label(type, executable)
                }
            }
        }

        assertEquals(
            mapOf(
                "ServedBytesVerified" to listOf("ServedBytesVerified\$Companion.verifyServedBytes"),
                "DeliveryEvidence" to listOf("DeliveryEvidence\$Companion.verifyPlaintextBytes"),
            ),
            doors,
            "a second published function returning one of these would be a second way to obtain " +
                "delivery evidence, and §10.4's ordering is only as strong as the narrowest door",
        )
    }
}
