package dev.eryalabs.nenya.bid

import java.io.File
import java.lang.reflect.Constructor
import java.lang.reflect.Executable
import java.lang.reflect.Method
import java.lang.reflect.Modifier
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * §6's load-bearing structural rule — "An implementation MUST NOT advance any order state on the
 * basis of a bid, public or private" — made **unrepresentable** rather than merely untested, plus
 * the round's headline rule reaching this package.
 *
 * The sweep is the one `PaymentStructureTest` specifies, over `dev/eryalabs/nenya/bid`, and every
 * note there applies here:
 *
 * - **`java.lang.reflect` only.** `kotlin-reflect` is not on any classpath and STOP RULE 11 forbids
 *   adding one. `KClass.members` and `KClass.constructors` compile and then throw
 *   `KotlinReflectionNotSupportedError`; `kotlin.reflect.full.*` does not compile at all.
 * - **`getResources`, plural.** The singular form resolves to the **test** output directory,
 *   because `build/classes/kotlin/jvm/test` precedes `build/classes/kotlin/jvm/main` on the test runtime
 *   classpath and this repo mirrors package names into its test tree. A sweep built on it would
 *   enumerate this very file's class, never see [Bid], and pass with the implementation entirely
 *   absent.
 * - **Classes asserted by name.** A count is satisfied by whatever the wrong classpath entry
 *   happened to contain, which is exactly the failure the plural form exists to avoid.
 */
class BidStructureTest {

    private companion object {

        const val PACKAGE: String = "dev.eryalabs.nenya.bid"

        /** The order package, which nothing here may take, return or extend (§6, §11.2). */
        const val ORDER_PACKAGE: String = "dev.eryalabs.nenya.order"

        /** T7's types a bid MUST NOT be usable as, named so a rename there turns this red. */
        val ORDER_TYPES: List<String> = listOf("OrderEvent", "OrderState", "Order", "OrderOutcome")

        /** The classes this sweep is *about*, by name rather than by count. */
        val EXPECTED_BY_NAME: Set<String> = setOf(
            "Bid",
            "BidRejection",
            "BidException",
            "BidVocabulary",
        )

        /**
         * Every place on the published surface where a `String` may be a parameter, pinned by name.
         *
         * A new one turns this red and forces a human to say why it is not a counterparty's status
         * string arriving as evidence of something. Each of these is either an event field the
         * decoder was handed, a diagnostic message, or a compiler-generated enum lookup.
         */
        val STRING_PARAMETERS_PERMITTED: Set<String> = setOf(
            "Bid.<init>",           // the bidder pubkey, content, relay hints — event fields
            "BidException.<init>",  // the tag name and the rejection message
            "BidRejection.valueOf", // generated by the Kotlin compiler for enums
        )

        fun mainClasses(): List<Class<*>> {
            val loader = BidStructureTest::class.java.classLoader
            val urls = loader.getResources(PACKAGE.replace('.', '/')).toList()
            val main = urls.firstOrNull { it.path.contains("/classes/kotlin/jvm/main/") }
                ?: fail(
                    "no /classes/kotlin/jvm/main/ URL for $PACKAGE among $urls — the sweep would " +
                        "otherwise enumerate the test output directory and pass with no implementation",
                )
            val directory = File(main.toURI())
            val files = directory.listFiles { file: File -> file.name.endsWith(".class") }
                ?: fail("${directory.absolutePath} is not a readable directory")
            assertTrue(files.isNotEmpty(), "${directory.absolutePath} holds no classes")
            // The class files this package compiled to at commit 6432814, pinned as a floor so a
            // partial output directory after a source-layout move goes red instead of sweeping less.
            val pinned = 8
            assertTrue(
                files.size >= pinned,
                "${directory.absolutePath} holds ${files.size} class file(s); at least $pinned were pinned",
            )
            return files.map { Class.forName("$PACKAGE.${it.name.removeSuffix(".class")}", false, loader) }
        }

        fun publishedClasses(): List<Class<*>> =
            mainClasses().filter { Modifier.isPublic(it.modifiers) && !it.isSynthetic }

        /** Constructors and own public methods, minus everything a client cannot name. */
        fun publishedExecutables(type: Class<*>): List<Executable> =
            type.constructors.toList() +
                type.methods.filter {
                    it.declaringClass == type && !it.isSynthetic && !it.isBridge && '$' !in it.name
                }

        fun label(type: Class<*>, executable: Executable): String {
            val simple = type.name.removePrefix("$PACKAGE.")
            val member = if (executable is Constructor<*>) "<init>" else executable.name
            return "$simple.$member"
        }
    }

    @Test
    fun `the sweep finds the classes it is about, by name`() {
        val found = mainClasses().map { it.name.removePrefix("$PACKAGE.") }.toSet()

        for (expected in EXPECTED_BY_NAME) {
            assertTrue(
                expected in found,
                "$expected was not among the main classes of $PACKAGE; found $found",
            )
        }
    }

    @Test
    fun `no published constructor or method accepts a Boolean`() {
        // Its own by-name guard rather than only the `inspected` floor below: every other test here
        // would turn red if `mainClasses()` started resolving to the test output directory, and this
        // one would not, because the test tree alone satisfies a bare member count.
        val published = publishedClasses()
        val found = published.map { it.name.removePrefix("$PACKAGE.") }.toSet()
        assertTrue(
            EXPECTED_BY_NAME.all { it in found },
            "the Boolean sweep must be looking at $EXPECTED_BY_NAME, not at whatever classpath " +
                "entry it happened to land on; it found $found",
        )

        var inspected = 0
        for (type in published) {
            for (executable in publishedExecutables(type)) {
                inspected++
                for (parameter in executable.parameterTypes) {
                    assertFalse(
                        parameter == java.lang.Boolean.TYPE || parameter == java.lang.Boolean::class.java,
                        "${label(type, executable)} takes a Boolean. A bid is decoded from an event " +
                            "this library hashed for itself; a function that can be told the answer " +
                            "is not a decoder, and a relay's say-so is not evidence of anything.",
                    )
                }
            }
        }
        assertTrue(inspected > 10, "the sweep inspected only $inspected members, which is not the package")
    }

    @Test
    fun `every published String parameter is on the pinned list`() {
        val found = mutableSetOf<String>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                if (executable.parameterTypes.any { it == String::class.java }) {
                    found += label(type, executable)
                }
            }
        }

        assertEquals(
            STRING_PARAMETERS_PERMITTED,
            found,
            "the set of published members taking a String must match the pinned list exactly. A " +
                "new entry may be a status string arriving as evidence; a missing entry means the " +
                "sweep stopped seeing the package.",
        )
    }

    /**
     * §6's rule, enforced where an implementer would breach it: "A bid is not an acceptance and
     * creates no obligation on anyone... An implementation MUST NOT advance any order state on the
     * basis of a bid, public or private."
     *
     * T7 closes the other direction — its transition function refuses a `type=6` private bid from
     * all eleven states — and a codec can satisfy that while still handing a caller an `OrderEvent`
     * built out of a public bid, which the state machine would then accept because it is a
     * well-formed event of a type it implements. So nothing published here may take, return or
     * extend an order-package type, and [Bid] is not assignable to one. There is no value of the
     * right shape to feed the machine.
     */
    @Test
    fun `nothing in this package takes, returns or extends an order-package type`() {
        for (type in publishedClasses()) {
            var supertype: Class<*>? = type.superclass
            while (supertype != null) {
                assertFalse(
                    supertype.name.startsWith("$ORDER_PACKAGE."),
                    "${type.name} extends ${supertype.name}",
                )
                supertype = supertype.superclass
            }
            for (implemented in type.interfaces) {
                assertFalse(
                    implemented.name.startsWith("$ORDER_PACKAGE."),
                    "${type.name} implements ${implemented.name}",
                )
            }
            for (executable in publishedExecutables(type)) {
                // The **generic** types, not the erased ones. A published `fun x(): List<OrderEvent>`
                // erases to `List` and would satisfy a `returnType` check while handing a caller a
                // pile of order events — which is the whole thing §6 forbids, wrapped in a
                // collection. `typeName` prints the parameterised form, so `contains` sees it.
                val mentioned = (
                    executable.genericParameterTypes.toList() +
                        listOfNotNull((executable as? Method)?.genericReturnType)
                    ).map { it.typeName }
                for (other in mentioned) {
                    assertFalse(
                        other.contains("$ORDER_PACKAGE."),
                        "${label(type, executable)} mentions $other; §6 forbids advancing any " +
                            "order state on the basis of a bid, and a bid layer that can hand the " +
                            "state machine a value is a bid layer that can",
                    )
                }
            }
        }
    }

    /**
     * The same rule stated the way an implementer would breach it, so the refusal is legible in a
     * stack trace rather than only in the sweep above: a [Bid] is not an order event, an order
     * state, or an order.
     *
     * Asserted by name against the order package's own classes, loaded through the same loader, so
     * a rename there turns this red rather than quietly making it vacuous.
     */
    @Test
    fun `a Bid is not assignable to an order event, an order state or an order`() {
        val loader = BidStructureTest::class.java.classLoader
        val bid = Class.forName("$PACKAGE.Bid", false, loader)

        for (name in ORDER_TYPES) {
            // Resolved rather than probed: a rename in T7's package must turn this red, because a
            // test that skipped what it could not find would pass most loudly on the day the type
            // it is about was renamed.
            val orderType = try {
                Class.forName("$ORDER_PACKAGE.$name", false, loader)
            } catch (absent: ClassNotFoundException) {
                fail("$ORDER_PACKAGE.$name was not found, so this test proved nothing: $absent")
            }
            assertFalse(
                orderType.isAssignableFrom(bid),
                "§6: a bid creates no obligation on anyone, so a Bid MUST NOT be usable as a $name",
            )
        }
    }

    /**
     * The narrowest door, as T8 puts it: every published function returning a [Bid] is one an event
     * had to pass §4.1's id check to reach. A second one would be a second way to decode a bid this
     * library never hashed.
     */
    @Test
    fun `the only published function returning a bid is decode`() {
        val doors = mutableListOf<String>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                val returned = (executable as? Method)?.returnType ?: continue
                if (returned.name == "$PACKAGE.Bid") doors += label(type, executable)
            }
        }

        assertEquals(listOf("Bid\$Companion.decode"), doors)
    }

    /** The published constructor [Bid] does carry is the internal one, which is not a door. */
    @Test
    fun `a bid cannot be built from values a caller chose`() {
        val type = publishedClasses().single { it.name == "$PACKAGE.Bid" }

        for (constructor in type.constructors) {
            assertTrue(
                constructor.parameterTypes.any { it.name == "dev.eryalabs.nenya.wire.EventId" },
                "Kotlin publishes an `internal` constructor to the JVM, so this one is reachable " +
                    "from Java — but only with an EventId, which only T8's recomputation produces. " +
                    "A constructor taking loose values would be a bid nobody checked.",
            )
        }
    }
}
