package dev.eryalabs.nenya.listing

import dev.eryalabs.nenya.money.FeeTerm
import dev.eryalabs.nenya.tag.NenyaKind
import kotlin.js.JsName
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Decision **P**'s proof, over a generated corpus: **build → decode → build → the same bytes**.
 *
 * ### Why this is the proof and not a round trip of convenience
 *
 * The writer and the decoder are two halves of one wire contract, and the way they come apart is
 * silent: a row emitted twice, an optional row emitted when it should have been omitted, a value
 * canonicalised one way on the way out and another on the way back in, a value the decode cannot see
 * at all. None of those throws. All of them change §4.1's event id, which is the hash of the tags
 * **in order**, so comparing the canonical serialisation of the first build with that of the second
 * is one assertion that covers every one.
 *
 * The second build is assembled **only from what `Listing.decode` reports** — see
 * [ListingWriterFixtures.reauthored] — which makes the property stronger than a self-comparison in
 * exactly the way that matters: a decoder that dropped a value would make the rebuild differ, and a
 * writer that emitted something its decoder cannot see would too.
 *
 * ### What a round trip cannot catch, said out loud
 *
 * A **symmetric** error is invisible to it. Swap the two `t` tokens the writer emits and the decode
 * reports them swapped, the reconstruction drops the same two, and the rebuild reproduces the swap
 * byte for byte — a fixed point of a wrong writer. That was measured, not assumed: with the pair
 * reversed in `ListingWriter.row` this file's byte comparison stays green and three other assertions
 * go red. So the `t` ordering is asserted **positively** below, against §4.5's and §5.1's/§5.2's own
 * constants, and the thing that holds the whole emission order to the document is the inverse
 * control in `ListingWriterTest` — where one side of the comparison is `spec/NENYA-1.md` rather than
 * this writer.
 *
 * ### The non-vacuity floors
 *
 * Three, because a round-trip property is the easiest kind to pass for the wrong reason:
 *
 * 1. **Every case is built and decoded.** A corpus the writer refused would round-trip trivially,
 *    so the count of accepted builds is asserted equal to the corpus size.
 * 2. **Every optional §5.3 row appears present and absent**, derived from
 *    [ListingWriterFixtures.OPTIONAL_ROWS]. A row that was always absent is a row these bytes never
 *    carried.
 * 3. **The corpus is not one listing repeated.** The number of distinct canonical serialisations is
 *    asserted equal to the number of cases.
 *
 * `ListingWriterTest` carries the inverse control — the document's own worked listings, parsed out of
 * `spec/NENYA-1.md` and rebuilt — because everything here is generated by code in this repository
 * and a generator cannot say whether the writer agrees with the specification.
 */
class ListingWriterPropertyTest {

    private companion object {

        /**
         * 600 listings, against T40's floor of 500.
         *
         * Each case draws every optional §5.3 row independently, so the corpus covers each of them in
         * both states many times over; the floors below assert that rather than assuming it.
         */
        const val CORPUS: Int = 600

        /**
         * The seven characters §4.1 gives a shortcut escape, by code point: quote, backslash,
         * backspace, form feed, newline, carriage return, tab.
         *
         * By code point rather than as a string literal so the set is unmistakable — and form feed is
         * the one that matters, because it is one of the seven *and* below `0x20`, so leaving it out
         * would count it under rule 2 and overstate what the corpus reached.
         */
        val SHORTCUT_ESCAPES: List<Int> = listOf(0x22, 0x5C, 0x08, 0x0C, 0x0A, 0x0D, 0x09)

        /** `0x7f`, which §4.1 emits verbatim because rule 3 covers everything at or above `0x20`. */
        const val DEL: Int = 0x7F
    }

    /**
     * The round trip, and the assertion the task is about: the two emitted events are byte-identical.
     *
     * The `t` ordering is asserted **positively**, before the rebuild drops the two tokens the writer
     * emits itself, and it is not redundant with the byte comparison: that drop is the one place the
     * reconstruction knows something the decode did not tell it, so a swapped pair is a fixed point of
     * the round trip. See this class's note on what a round trip cannot catch.
     */
    @JsName("every_built_listing_decodes_and_rebuilds_to_the_identical_event")
    @Test
    fun `every built listing decodes and rebuilds to the identical event`() {
        val cases = ListingWriterFixtures.cases(CORPUS)
        assertEquals(CORPUS, cases.size)

        var built = 0
        val serialisations = mutableSetOf<String>()
        for (case in cases) {
            val first = ListingWriterFixtures.built(
                ListingWriterFixtures.build(case.kind, case.listing),
                "case ${case.index} as kind:${case.kind}",
            )
            val decoded = ListingWriterFixtures.decode(first)

            assertEquals(case.kind, decoded.kind, "case ${case.index}")
            assertEquals(
                listOf("nenya", ListingSide.requiredOn(case.kind)?.token),
                decoded.topics.take(ListingWriterFixtures.FIXED_TOPICS),
                "case ${case.index}: §4.5's discovery token then §5.1's or §5.2's side token, in " +
                    "that order — the reconstruction below drops exactly these two",
            )

            val second = ListingWriterFixtures.built(
                ListingWriterFixtures.build(case.kind, ListingWriterFixtures.reauthored(decoded)),
                "case ${case.index} rebuilt from what the decode reports",
            )
            ListingWriterFixtures.assertSameBytes(first, second, "case ${case.index}")

            built++
            serialisations += first.canonicalSerialisation()
        }

        assertEquals(CORPUS, built, "a corpus the writer refused would round-trip vacuously")
        assertEquals(
            CORPUS,
            serialisations.size,
            "the corpus must be $CORPUS different listings, not one listing $CORPUS times",
        )
    }

    /**
     * Every optional §5.3 row is drawn present **and** absent across the corpus.
     *
     * The rows are derived from [ListingWriter.TAG_ORDER] minus the ones §5.3 marks MUST on every
     * kind, so a row added to §5.3 and to the writer joins this floor without anybody editing a list
     * here. A row that was always absent would leave the round trip above silent about it.
     */
    @JsName("the_corpus_draws_every_optional_s5_3_row_present_and_absent")
    @Test
    fun `the corpus draws every optional §5_3 row present and absent`() {
        val present = mutableSetOf<String>()
        val absent = mutableSetOf<String>()
        val rows = ListingWriterFixtures.OPTIONAL_ROWS
        assertTrue(rows.isNotEmpty(), "§5.3 must have optional rows for this floor to be about")

        for (case in ListingWriterFixtures.cases(CORPUS)) {
            val event = ListingWriterFixtures.built(
                ListingWriterFixtures.build(case.kind, case.listing),
                "case ${case.index}",
            )
            val names = event.tags.map { it[0] }.toSet()
            for (row in rows) if (row in names) present += row else absent += row
        }

        assertEquals(rows.toSet(), present, "these optional rows are never emitted by the corpus")
        // `alt` is MUST on a request and the corpus always supplies it there — it is absent only
        // because a kind:30402 and a kind:30403 draw it. Every other optional row is drawn on
        // every kind.
        assertEquals(
            rows.toSet(),
            absent,
            "these optional rows are always emitted, so the round trip never saw them absent",
        )
    }

    /**
     * The corpus reaches the shapes §8.1 and §5.3 distinguish, counted rather than hoped for.
     *
     * §8.1's three `fee` cases are the ones a writer collapses by accident — [FeeTerm.Absent] and a
     * stated zero agree on the number and disagree on the wire — and §5.3's two `image` arities are
     * the ones §5.1's "unmodified NIP-99" makes legal. A corpus that drew only one of each would make
     * the round trip above pass over the branch that matters.
     */
    @JsName("the_corpus_reaches_both_fee_arities_the_stated_zero_and_both_image_arities")
    @Test
    fun `the corpus reaches both fee arities, the stated zero and both image arities`() {
        var absentFee = 0
        var statedZeroFee = 0
        var feeWithRecipient = 0
        var imageWithDimensions = 0
        var imageWithout = 0
        var extensions = 0
        var mixedCaseTopics = 0

        for (case in ListingWriterFixtures.cases(CORPUS)) {
            val event = ListingWriterFixtures.built(
                ListingWriterFixtures.build(case.kind, case.listing),
                "case ${case.index}",
            )
            val fee = event.tags.singleOrNull { it[0] == "fee" }
            when {
                fee == null -> absentFee++
                fee.size == 2 -> statedZeroFee++
                else -> feeWithRecipient++
            }
            for (image in event.tags.filter { it[0] == "image" }) {
                if (image.size == 3) imageWithDimensions++ else imageWithout++
            }
            if (case.listing.extraTags.isNotEmpty()) extensions++
            if (case.listing.topics.any { it != it.lowercase() }) mixedCaseTopics++
        }

        assertTrue(absentFee > 0, "§8.1's absent term was never drawn")
        assertTrue(statedZeroFee > 0, "§8.1's stated two-element `fee` was never drawn")
        assertTrue(feeWithRecipient > 0, "§8.1's three-element form was never drawn")
        assertTrue(imageWithDimensions > 0, "§5.3's three-element `image` was never drawn")
        assertTrue(imageWithout > 0, "NIP-99's two-element `image` was never drawn")
        assertTrue(extensions > 0, "§4.3's unknown-tag preservation was never exercised")
        assertTrue(mixedCaseTopics > 0, "§5.3's lowercase-on-write rule was never exercised")
    }

    /**
     * §4.1's three escaping rules are reached, because the id the round trip compares is computed
     * over the escaped bytes.
     *
     * Asserted over the values the writer actually emitted: what matters is that the characters §4.1
     * gives a shortcut escape, the ones needing its `\u00XX` form, a non-BMP character, and the two
     * it deliberately leaves alone all appear inside them. A corpus of plain ASCII would make the
     * round trip above prove nothing about §4.1 at all.
     */
    @JsName("the_corpus_puts_s4_1s_escaping_cases_inside_the_values_the_writer_emits")
    @Test
    fun `the corpus puts §4_1's escaping cases inside the values the writer emits`() {
        var withShortcut = 0
        var withControl = 0
        var withNonBmp = 0
        var withSlash = 0
        var withDel = 0

        for (case in ListingWriterFixtures.cases(CORPUS)) {
            val event = ListingWriterFixtures.built(
                ListingWriterFixtures.build(case.kind, case.listing),
                "case ${case.index}",
            )
            val text = event.tags.flatten().joinToString("") + event.content
            if (text.any { it.code in SHORTCUT_ESCAPES }) withShortcut++
            // Rule 2's case: below 0x20 and not one of the seven.
            if (text.any { it.code < 0x20 && it.code !in SHORTCUT_ESCAPES }) withControl++
            if (text.any { it.isHighSurrogate() }) withNonBmp++
            if (text.any { it == '/' }) withSlash++
            if (text.any { it.code == DEL }) withDel++
        }

        assertTrue(withShortcut > 0, "§4.1's seven shortcut escapes were never reached")
        assertTrue(withControl > 0, "§4.1's six-character escape for a control character was not reached")
        assertTrue(withNonBmp > 0, "§4.1's UTF-8 rule for a non-BMP character was never reached")
        assertTrue(withSlash > 0, "the solidus, which §4.1 never escapes, was never reached")
        assertTrue(withDel > 0, "DEL, which §4.1 emits verbatim because it is above 0x20, was not reached")
    }

    /** All three kinds are built, in roughly equal numbers, so neither side of the board is idle. */
    @JsName("the_corpus_covers_all_three_listing_kinds")
    @Test
    fun `the corpus covers all three listing kinds`() {
        val counts = mutableMapOf<Int, Int>()
        for (case in ListingWriterFixtures.cases(CORPUS)) {
            counts[case.kind] = (counts[case.kind] ?: 0) + 1
        }

        assertEquals(NenyaKind.LISTING_KINDS, counts.keys, "§5.1's two kinds and §5.2's one")
        for ((kind, count) in counts) {
            assertTrue(count > CORPUS / 4, "kind:$kind was drawn only $count time(s) in $CORPUS")
        }
    }
}
