package dev.eryalabs.nenya.payment

import java.io.File
import java.lang.reflect.Executable
import java.lang.reflect.Modifier
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * The structural half of §9.1 and STOP RULE 12, enforced by reflection rather than by review.
 *
 * §9.1 says a wallet's boolean, a counterparty's status string and a relay's acceptance are
 * not evidence. A code review can only assert that today's code obeys that; this file asserts
 * it about whatever is in the package tomorrow, which is when somebody adds
 * `verify(..., walletSaysPaid: Boolean)` in a hurry.
 *
 * ### `java.lang.reflect` only
 *
 * `kotlin-reflect` is not on any classpath and STOP RULE 11 forbids adding one. The two
 * failure modes differ and both are traps: `KClass.members` and `KClass.constructors` compile
 * and then throw `KotlinReflectionNotSupportedError` at run time, while `kotlin.reflect.full.*`
 * does not compile at all. So: `getConstructors()`, `getMethods()`, `getParameterTypes()`,
 * `Modifier`, and nothing else.
 *
 * ### Why `getResources`, plural
 *
 * `ClassLoader.getResource("dev/eryalabs/nenya/payment")` resolves to the **test** output
 * directory, because `build/classes/kotlin/jvm/test` precedes `build/classes/kotlin/jvm/main` on the
 * test runtime classpath and this repo mirrors package names into its test tree. A sweep built
 * on the singular form would enumerate this very file's class, never see [VerifiedPayment],
 * and pass with the implementation entirely absent. [mainClasses] therefore takes the plural
 * form and selects the `/classes/kotlin/jvm/main/` URL, failing loudly if there is none.
 *
 * ### What "the published surface" means here
 *
 * A JVM-public class, and on it: its public constructors, plus its public methods declared on
 * the class itself whose names carry no `$`. The `$` filter removes Kotlin's synthetic
 * accessors and its name-mangled `internal` members, which are public in the bytecode but are
 * not something a client can call by writing the name down. Inherited `java.lang.Object` and
 * `java.lang.Enum` methods are excluded by the declaring-class filter.
 */
class PaymentStructureTest {

    private companion object {

        const val PACKAGE: String = "dev.eryalabs.nenya.payment"

        /**
         * The classes this sweep is *about*. Asserted by name rather than by count: a count is
         * satisfied by whatever the wrong classpath entry happened to contain, which is exactly
         * the failure the plural `getResources` above exists to avoid.
         */
        val EXPECTED_BY_NAME: Set<String> =
            setOf("VerifiedPayment", "Preimage", "PaymentHash", "Payee")

        /**
         * Every place on the published surface where a `String` may be a parameter, pinned by
         * name. A new one turns this red and forces a human to say why it is not a status
         * string being smuggled in as evidence. Each of these is either a hex reader (§4.3's
         * encoding, not a status), a diagnostic message, or a compiler-generated enum lookup.
         */
        val STRING_PARAMETERS_PERMITTED: Set<String> = setOf(
            "PaymentHash\$Companion.ofHex",       // §4.3 hex, 64 characters, either case
            "Preimage\$Companion.ofHex",          // §4.3 hex, 64 characters, lowercase only
            "PaymentException.<init>",            // the human-readable rejection message
            "Payee.valueOf",                      // generated by the Kotlin compiler for enums
            "PaymentCheck.valueOf",               // ditto
            "PaymentRejection.valueOf",           // ditto
        )

        fun mainClasses(): List<Class<*>> {
            val loader = PaymentStructureTest::class.java.classLoader
            val urls = loader.getResources(PACKAGE.replace('.', '/')).toList()
            val main = urls.firstOrNull { it.path.contains("/classes/kotlin/jvm/main/") }
                ?: fail(
                    "no /classes/kotlin/jvm/main/ URL for $PACKAGE among $urls — the sweep would " +
                        "otherwise enumerate the test output directory and pass with no implementation",
                )
            val directory = File(main.toURI())
            val files = directory.listFiles { file: File -> file.name.endsWith(".class") }
                ?: fail("${directory.absolutePath} is not a readable directory")
            assertTrue(files.isNotEmpty(), "${directory.absolutePath} holds no classes")
            // The class files this package compiled to at commit 6432814, pinned as a floor so a
            // partial output directory after a source-layout move goes red instead of sweeping less.
            val pinned = 16
            assertTrue(
                files.size >= pinned,
                "${directory.absolutePath} holds ${files.size} class file(s); at least $pinned were pinned",
            )
            return files.map { Class.forName("$PACKAGE.${it.name.removeSuffix(".class")}", false, loader) }
        }

        fun publishedClasses(): List<Class<*>> =
            mainClasses().filter { Modifier.isPublic(it.modifiers) && !it.isSynthetic }

        /** Constructors and own public methods, minus everything a client cannot name. */
        fun publishedExecutables(type: Class<*>): List<Executable> =
            type.constructors.toList() +
                type.methods.filter {
                    it.declaringClass == type && !it.isSynthetic && !it.isBridge && '$' !in it.name
                }

        fun label(type: Class<*>, executable: Executable): String {
            val simple = type.name.removePrefix("$PACKAGE.")
            val member = if (executable is java.lang.reflect.Constructor<*>) "<init>" else executable.name
            return "$simple.$member"
        }
    }

    @Test
    fun `the sweep finds the classes it is about, by name`() {
        val found = mainClasses().map { it.name.removePrefix("$PACKAGE.") }.toSet()

        for (expected in EXPECTED_BY_NAME) {
            assertTrue(
                expected in found,
                "$expected was not among the main classes of $PACKAGE; found $found",
            )
        }
    }

    @Test
    fun `VerifiedPayment has no constructor for a client to reach`() {
        val type = mainClasses().single { it.name == "$PACKAGE.VerifiedPayment" }

        assertTrue(type.isInterface, "an interface has no constructor to synthesise an accessor for")
        assertEquals(
            0,
            type.constructors.size,
            "a private constructor plus a companion factory emits a *public synthetic* constructor " +
                "with a trailing DefaultConstructorMarker, which a Java client can call with null",
        )
        assertTrue(
            type.declaredConstructors.none { it.isSynthetic },
            "not even a synthetic constructor may exist on ${type.name}",
        )
        assertTrue(
            type.isSealed,
            "the JVM PermittedSubclasses attribute is what stops another module implementing " +
                "this interface; it is emitted only from JDK 17 upward, so a toolchain drop " +
                "would silently remove it while every other assertion here stayed green",
        )
    }

    @Test
    fun `every implementation of VerifiedPayment is non-public`() {
        val classes = mainClasses()
        val type = classes.single { it.name == "$PACKAGE.VerifiedPayment" }
        val implementations = classes.filter { it != type && type.isAssignableFrom(it) }

        assertTrue(
            implementations.isNotEmpty(),
            "the sweep must actually find an implementation; the two assertions above are true of " +
                "any interface at all and would pass over a public one",
        )
        for (implementation in implementations) {
            assertFalse(
                Modifier.isPublic(implementation.modifiers),
                "${implementation.name} implements VerifiedPayment and is JVM-public, so a client " +
                    "can construct evidence of a payment that was never made",
            )
        }
    }

    @Test
    fun `no published constructor or method accepts a Boolean`() {
        var inspected = 0
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                inspected++
                for (parameter in executable.parameterTypes) {
                    assertFalse(
                        parameter == java.lang.Boolean.TYPE || parameter == java.lang.Boolean::class.java,
                        "${label(type, executable)} takes a Boolean. §9.1: a wallet's isPaid is not " +
                            "evidence, and a function that can be told the answer is not a verifier",
                    )
                }
            }
        }
        assertTrue(inspected > 10, "the sweep inspected only $inspected members, which is not the package")
    }

    @Test
    fun `every published String parameter is on the pinned list`() {
        val found = mutableSetOf<String>()
        for (type in publishedClasses()) {
            for (executable in publishedExecutables(type)) {
                if (executable.parameterTypes.any { it == String::class.java }) {
                    found += label(type, executable)
                }
            }
        }

        assertEquals(
            STRING_PARAMETERS_PERMITTED,
            found,
            "the set of published members taking a String must match the pinned list exactly. A new " +
                "entry may be a status string arriving as evidence (§9.1); a missing entry means the " +
                "sweep stopped seeing the package.",
        )
    }

    @Test
    fun `the verifier takes a preimage and a payment hash, and nothing that can assert`() {
        val companion = mainClasses().single { it.name == "$PACKAGE.VerifiedPayment\$Companion" }
        val verify = companion.methods.single { it.name == "verify" }

        assertEquals(
            listOf(Payee::class.java, PaymentHash::class.java, Preimage::class.java),
            verify.parameterTypes.toList(),
            "§9.2 check 3 takes a preimage and the hash to check it against; anything else on this " +
                "parameter list is something a counterparty could say",
        )
        assertEquals(VerifiedPayment::class.java, verify.returnType)
    }
}
